### ISSUE TITLE
build: configure.ac hard-codes the pkg-config command

### ISSUE THREAD

**Issue by tgurr** [kdave/btrfs-progs#101]
Right now the pkg-config command is hard-coded in configure.ac, which may result in build errors on system and cross environments that have prefixed toolchains, e.g. /usr/x86_64-pc-linux-gnu/bin/x86_64-pc-linux-gnu-pkg-config.

[0001-configure.ac-Consistently-use-PKG_CONFIG.txt](https://github.com/kdave/btrfs-progs/files/1737573/0001-configure.ac-Consistently-use-PKG_CONFIG.txt)

Please see the attached patch, it has been written a while ago but it seems it hasn't been submitted for upstream inclusion.

**Comment by kdave** [comment]
Applied, thanks.
