### ISSUE TITLE
"ftw subdir walk of <dir> failed: No such file or directory" error since commit "btrfs-progs: mkfs/rootdir: Use over-reserve method to make size estimate easier"

### ISSUE THREAD

**Issue by kanavin** [kdave/btrfs-progs#109]
Recent versions of btrfs-progs are failing with an error where previous versions worked fine:

$ mkfs.btrfs -b 163636428 -r /var/tmp/wic.oe-selftest/tmp.wic.qqqhmadz/rootfs_copy   -U 157e7723-9772-4696-a81f-1c6fb896a56e /var/tmp/wic.oe-selftest/tmp.wic.qqqhmadz/rootfs_None.2.btrfs
ftw subdir walk of /var/tmp/wic.oe-selftest/tmp.wic.qqqhmadz/rootfs_copy failed: No such file or directory
btrfs-progs v4.14.1-23-g561cef37
See http://btrfs.wiki.kernel.org for more information.

I've done bisection and established that this commit introduces the issue:

commit 599a0abed5649727dc3b6ec4ec373ba30253df45
Author: Qu Wenruo <wqu@suse.com>
Date:   Thu Oct 19 10:11:07 2017 +0800

    btrfs-progs: mkfs/rootdir: Use over-reserve method to make size estimate easier

I've also ran mkfs.btrfs under strace, and it seems as though it chokes on a symbolic link that is not pointing to an actual file (something that is quite common with rootfs trees), but I'm not entirely sure that is the reason. If you can suggest further diagnostics, I'd be happy to help.

**Comment by adam900710** [comment]
Is that rootdir itself a reflink? Or something inside is a bad reflink?

I'd better double check the ftw related modifications.

2018年3月14日 00:52，"Alexander Kanavin" <notifications@github.com>写道：

**Comment by kanavin** [comment]
Something inside rootdir is a symlink to a file that doesn't exist. E.g.

/var/tmp/rootfs/dir/symlink -> /usr/bin/some_file

where /usr/bin/some_file does not exist, but /var/tmp/rootfs/usr/bin/some_file does exist. So on the eventual image the symlink would be correct. Strace seems to point out that the directory scan stops when such symlink is encountered.

**Comment by adam900710** [comment]
Sorry for being so late.

Fix sent https://patchwork.kernel.org/patch/10312225/

Thanks for the report.

**Comment by kanavin** [comment]
Thanks, I can confirm that the issue is resolved.

**Comment by kdave** [comment]
Patch added to devel, thanks.
