### ISSUE TITLE
Incorrect parsing of key.offset when a snapshot is created

### ISSUE THREAD

**Issue by lorddoskias** [kdave/btrfs-progs#111]
When a snapshot is created it's root item's key.offset field contains the transaction id when this snapshot was created. Issuing btrfs inspect-internal dump-tree, however, parses this number and tries to give it a name. For example: 

```
file tree key (257 ROOT_ITEM QUOTA_TREE)
leaf 30818304 items 7 free space 15638 generation 9 owner 257
leaf 30818304 flags 0x1(WRITTEN) backref revision 1
fs uuid 5203ac6c-f56b-4f29-abff-35984ceec23a
chunk uuid 1d77b709-52af-47d3-bd43-3827f5a40afb
```

Root item from root tree: 

```
  item 12 key (257 ROOT_ITEM QUOTA_TREE) itemoff 13183 itemsize 439
                generation 9 root_dirid 256 bytenr 30818304 level 0 refs 1
                lastsnap 8 byte_limit 0 bytes_used 16384 flags 0x0(none)
                uuid 7f18abf7-9074-6742-ad05-9ec512edca3a
                ctransid 9 otransid 8 stransid 0 rtransid 0
                ctime 1521450606.594243650 (2018-03-19 09:10:06)
                otime 1521450602.136276277 (2018-03-19 09:10:02)
                drop key (0 UNKNOWN.0 0) level 0
```

In this case the snapshot happened to have been created in transaction 8, which coincides with `include/uapi/linux/btrfs_tree.h:#define BTRFS_QUOTA_TREE_OBJECTID 8ULL`

The correct behavior should really be - check if a snapshot and if yes, don't parse the offset just print the raw value. Alternatively, root item's key.offset is either 0 (in case of a subvol) and the transid in case of a snapshot. So just printing the numeric value *should* be enough.

**Comment by adam900710** [comment]
IIRC the offset should be the source subvolume id, not transid.

When does this behavior change?

**Comment by lorddoskias** [comment]
Apparently it's been like that forever. In create_pending_snapshot there is:  
```
/* record when the snapshot was created in key.offset */                
        key.offset = trans->transid;   
```

Most recent touch of this code has been in 2010 by Yan Zheng in a22285a6a323 ("Btrfs: Integrate metadata reservation with start_transaction") but this only moved the code in question.

**Comment by adam900710** [comment]
OK, in fact even for ROOT_ITEM, we have different meanings for different objectid.

For tree reloc tree, we did set offset to the objectid of its source root:
```
static struct btrfs_root *create_reloc_root(struct btrfs_trans_handle *trans,
                                        struct btrfs_root *root, u64 objectid)
...
        root_key.objectid = BTRFS_TREE_RELOC_OBJECTID;
        root_key.type = BTRFS_ROOT_ITEM_KEY;
        root_key.offset = objectid;
...
        ret = btrfs_insert_root(trans, fs_info->tree_root,
                                &root_key, root_item);
```

And that's the reason I added the print.
I'll update the output to handle this special case.

Thanks.

**Comment by adam900710** [comment]
Fix sent:

https://patchwork.kernel.org/patch/10292063/

BTW, is the reported-by tag correct?

**Comment by lorddoskias** [comment]
Yeah, i Just discovered that while inspecting some tree output I created the issue as a remained for something to be fixed but you beat me to it :)

**Comment by lorddoskias** [comment]
Fixed with the latest dev branch so closing it.
