### ISSUE TITLE
e2fsprogs-1.44.0+ breaks btrfs build

### ISSUE THREAD

**Issue by bdubbs** [kdave/btrfs-progs#121]
In e2fsprogs-1.44.0 (and .1) the ext2_ext_attr_entry structure changed the name of an element from e_value_block to e_value_inum.

This breaks the build in convert/source-ext2.c:

convert/source-ext2.c:425:13: error: ‘struct ext2_ext_attr_entry’ has no member named ‘e_value_block’; did you mean ‘e_value_offs’?
  if (entry->e_value_block != 0 || value_size > size ||
             ^~~~~~~~~~~~~
             e_value_offs
make: *** [Makefile:282: convert/source-ext2.o] Error 1

**Comment by adam900710** [comment]
Already fixed in devel branch.

https://github.com/kdave/btrfs-progs/commit/92ffad47b5c78ca119e798505e20f1b5cf7b7dd8

**Comment by kdave** [comment]
Will be fixed in 4.16.
