### ISSUE TITLE
filesystem show seems inconsistent on degraded RAID1

### ISSUE THREAD

**Issue by PAStheLoD** [kdave/btrfs-progs#143]
Hello!

On a just compiled current master, on Linux 4.15.0-22-generic #24-Ubuntu, with a only one part of a raid1 fs present:

```
$ sudo ./btrfs fi sh
Label: none  uuid: 3e55fdcf-d219-46a7-b8ce-400b38c35293
	Total devices 2 FS bytes used 1.07GiB
	devid    1 size 3.59GiB used 2.19GiB path /dev/sdb2
	devid    2 size 3.59GiB used 2.58GiB path /dev/sdb2
```

**Comment by adam900710** [comment]
Would you please provide the following dump?

```
btrfs ins dump-tree -t chunk /dev/sdb2
```

And, does `btrfs dev rescan` have any effect?

**Comment by PAStheLoD** [comment]
I think it's best to close this issue, as ... it turns out there were many problems with my setup. The USB pendrive was sort of faulty. (badblocks -w gave no errors, but a simple dd if=testfile of=/dev/sdb bs=1M  && dd if=/dev/sdb of=test2  && cmp testfile test  returned difference) And the cmdline.txt had rootflags=degraded to help uptime, which is a known Gotcha :/
