### ISSUE TITLE
Maximum file name length for subvolume

### ISSUE THREAD

**Issue by SmokinJoe98TA** [kdave/btrfs-progs#145]
I was lead to believe the maximum file name length was 255 characters.  Yet when trying to create a subvolume with a name of 255 characters, it fails with name too long.   To throw this error, a check of the name length is made, and if zero (how can this be too long?),  or greater than or EQUAL to BTRFS_VOL_NAME_MAX (255), then fail with name too long. 

Is this a bug in the code, or in the file name length really limited to 254 characters?

**Comment by suyj-fnst** [comment]
I made a patch and changed the file name length to 255, you can try it.

patch link:
https://patchwork.kernel.org/patch/10596907/

**Comment by SmokinJoe98TA** [comment]
Unfortunately, I have no way of testing this easily in my current environments,  however, i.e. rebuild in and install new driver.     The patch however does exactly what I would expect now.  Thanks!

**Comment by kdave** [comment]
Fixed in 4.19.
