### ISSUE TITLE
Feature Request: support of <BTRFS subvolume ID> to specify required subvolume 

### ISSUE THREAD

**Issue by MatthiasMiethke** [kdave/btrfs-progs#152]
This will be improvement in handling and for scripting, the ID is unique.
So not
btrfs subvolume delete /media/btrfs/os/ubuntu/var/lib/lxd/storage-pools/pool/images/bbb592c417b69ff8eac82df58ceeace2b4f58c09339e7ffc019a5069928648da
just like
btrfs subvolume delete ID 225

This is still supported by set-default [<subvolume>|<id> <path>]
There are two ways how to specify the subvolume, by <id> or by the <subvolume> path. The id can be obtained from btrfs subvolume list, btrfs subvolume show or btrfs inspect-internal rootid.

I think this sould supported at all btrfs subvolume commands.

**Comment by adam900710** [comment]
It could be supported by a new parameter like --subvolumeid=

We still needs a path to specifiy which mounted btrfs we're going to modify.

**Comment by MatthiasMiethke** [comment]
@adam900710 

Your right with the path, so more like 
btrfs subvolume delete –subvolumeid=255 /

in btrfs subvolume set-default it is used 
btrfs subvolume set-default 255 /

in my opinion, a shorter parameter name or no extra parameter is better
but this a decision that the developers have to do

**Comment by marcosps** [comment]
oops, I was planning to send a PR once I wrote some tests for it, and not sending notifications in this earlier version...

**Comment by marcosps** [comment]
Sent the patch to the linux-btrfs ML

**Comment by marcosps** [comment]
I'm working in the kernel side of these changes. Hopefully, it'l be enough to send to the ML.

**Comment by marcosps** [comment]
The kernel side changes are already in linux-next, only remaining the btrfs-progs changes.

**Comment by kdave** [comment]
The deletion by id has been added to devel, thanks.
