### ISSUE TITLE
change 'btrfs ready' to 'btrfs device ready' in 64-btrfs-dm.rules?

### ISSUE THREAD

**Issue by wangyugui** [kdave/btrfs-progs#161]
Hi,

Should we change 'btrfs ready' to 'btrfs device ready' in 64-btrfs-dm.rules?

Now, there is no command for 'btrfs ready', but 'btrfs device ready'.

Is this feature designed for device mapper multiple path  support?

Best regards.

**Comment by kdave** [comment]
The udev rule refers to builtin functionality of udev (in the systemd package), see `./src/udev/udev-builtin-btrfs.c` there. This does not have any relevance for device mapper and/or multipath support.

**Comment by wangyugui** [comment]
Thanks a lot.

'btrfs ready' is a builtin command  of systemd package /src/udev/udev-builtin-btrfs.c.

so no needs to change it to btrfs command in btrfs-progs packae.
