### ISSUE TITLE
btrfs restore restoring symlink fails on too many loops

### ISSUE THREAD

**Issue by tomasbrod** [kdave/btrfs-progs#164]
When restoring only symlinks with btrfs restore, it gives up restoring symlinks in directory with too many files. I think files skipped due to already being there count towards unsuccessful tries, which then triggers https://github.com/digint/btrfs-progs-btrbk/blob/master/cmds-restore.c#L1009 error message.

`We have looped trying to restore files in /usr/lib too many times to be making progress, stopping`

**Comment by dark-penguin** [comment]
This is still an issue in Ubuntu Eoan (April 2020). I was able to restore my system partition except /usr/share/man/man3 , which apparently contains too many symlinks. And I don't know if I can somehow regenerate it.

Maybe it should not give up without asking? I don't even understand what kind of "looping" is it talking about. And I don't see any option how to force it.

While we're at it, it would be good to have an option to force "looping" as much as necessary to recover any salvageable data. Without having to press Y every time. Yes, I am working on a filesystem image, I don't care how long it takes, I want all my data saved! And if I go to sleep in the process, I want to see the process finished in the morning, and not "Press Y to continue! (Also, some of your data was quietly discarded unless you save the output and search it for 'looped' later!)".

**Comment by kdave** [comment]
The looping in restore has been removed.
