### ISSUE TITLE
Background balance should check full-balance in advance

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#168]
The warning when full-balance is started in the background is pritnted too late, ie. in the forked process and the user does not see it nor is able to react.

To fix that, move the check before the fork in cmds-balance.c:cmd_balance_start

**Comment by CyberShadow** [comment]
Patch: https://patchwork.kernel.org/patch/11099359/

**Comment by kdave** [comment]
Thanks, patch added to devel.
