### ISSUE TITLE
progs can't detect newly initialised fs on an image

### ISSUE THREAD

**Issue by lorddoskias** [kdave/btrfs-progs#169]
The following set of commands give an error until an image is recognised by running 'blkid':

```
truncate -s 3g btrfs.img
mkfs.btrfs btrfs.img
btrrfs fi show .img
ERROR: not a valid btrfs filesystem: /root/btrfs.img
```

However the following commands succeed: 

```
root@ubuntu-virtual:~# blkid btrfs.img
btrfs.img: UUID="ea29379c-6b8d-4e4e-86c2-64d8d82f51bf" UUID_SUB="c59cde28-2ce3-414d-bfd1-e442e4cb58fa" TYPE="btrfs"
root@ubuntu-virtual:~# btrfs fi show btrfs.img
Label: none  uuid: ea29379c-6b8d-4e4e-86c2-64d8d82f51bf
	Total devices 1 FS bytes used 128.00KiB
	devid    1 size 3.00GiB used 331.12MiB path /root/btrfs.img
```

This likely due to the file system's image not being explicitly opened by `fi show` cmd. There might be other commands which fail similarly.

**Comment by kdave** [comment]
The image is detected as type BTRFS_ARG_REG, so 'fi show' could work with that if it's implemented.

**Comment by kdave** [comment]
Fixed in devel.
