### ISSUE TITLE
btrfs-convert doesn't call crc32c_optimization_init()...

### ISSUE THREAD

**Issue by elliotclee** [kdave/btrfs-progs#175]
...and as a result all conversions silently fall back to the old slow software crc32 functions. Here's a patch:

```
diff -up btrfs-progs-5.1/convert/main.c.faster-crc32 btrfs-progs-5.1/convert/main.c
--- btrfs-progs-5.1/convert/main.c.faster-crc32	2019-05-23 18:48:29.821234917 -0400
+++ btrfs-progs-5.1/convert/main.c	2019-05-23 18:49:23.677719540 -0400
@@ -1853,6 +1853,8 @@ int main(int argc, char *argv[])
 		return 1;
 	}
 
+	crc32c_optimization_init();
+
 	if (rollback) {
 		ret = do_rollback(file);
 	} else {

```

An alternative would be to change crc32c.c so that crc_function is initialized to NULL and then the crc32c_le function calls crc32c_optimization_init() if crc_function is NULL.

**Comment by elliotclee** [comment]
Here's an updated patch that also adds a progress indicator for the filesystem image creation step. Otherwise, when using data csumming, this step can run for a few hours without any feedback to the user...
[btrfs-progs-fastercrc+imageprogress.zip](https://github.com/kdave/btrfs-progs/files/3216745/btrfs-progs-fastercrc%2Bimageprogress.zip)

**Comment by adam900710** [comment]
Nice catch!

Although I'd prefer to make the optimization init call into __open_ctree_fd() so that we will never forget that anymore.

And just a kind reminder, btrfs development still prefer mail list for patch review.
Feel free to submit your patch to linux-btrfs@vger.kernel.org

Thanks.

**Comment by kdave** [comment]
> And just a kind reminder, btrfs development still prefer mail list for patch review.
> Feel free to submit your patch to linux-btrfs@vger.kernel.org

For drive-by fixes or report-with-a-patch I don't insist on sending it to the mailinglist. Developers know what to do and users that care enough to report the issues should not be bothered (too much) with the development process.

**Comment by kdave** [comment]
> Here's an updated patch that also adds a progress indicator for the filesystem image creation step. Otherwise, when using data csumming, this step can run for a few hours without any feedback to the user...
> [btrfs-progs-fastercrc+imageprogress.zip](https://github.com/kdave/btrfs-progs/files/3216745/btrfs-progs-fastercrc%2Bimageprogress.zip)

This is for another issue, I'm closing this one (the misisng crc init).
