### ISSUE TITLE
Missing reiserfs files

### ISSUE THREAD

**Issue by Gittyart** [kdave/btrfs-progs#179]
`make` results in error:
```
[CC]     convert/source-reiserfs.o
In file included from convert/source-reiserfs.c:30:0:
./convert/source-reiserfs.h:23:10: fatal error: reiserfs/misc.h: No such file or directory
 #include <reiserfs/misc.h>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:316: recipe for target 'convert/source-reiserfs.o' failed
make: *** [convert/source-reiserfs.o] Error 1
```

`source-reiserfs.h` file calls for the following:
```
#include <reiserfs/misc.h>
#include <reiserfs/io.h>
#include <reiserfs/reiserfs_lib.h>
#include <reiserfs/reiserfs_fs.h>
```
They don't seem to exist in either the git clone or the zip.

**Comment by kdave** [comment]
What version of the reiserfs library do you use? The minimum required is 3.6.27, that has the misc.h file.

**Comment by Gittyart** [comment]
You're correct. Apologies. I looked at the main page here thinking it was the latest and thought I had run my updated properly. I now have btrfs-progs v5.1. That worked and fixed my problem. I got to recover my HDD (3TB worth). Thank you!!!

**Comment by kdave** [comment]
Ok, closing.
