### ISSUE TITLE
Fix warnings -Waddress-of-packed-member

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#180]
There are lots of warnings during build, with gcc 9.1.1, eg.

```
cmds-balance.c: In function ‘parse_filters’:
cmds-balance.c:237:30: warning: taking address of packed member of ‘struct btrfs_balance_args’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  237 |    if (parse_profiles(value, &args->profiles)) {
```

**Comment by unquietwiki** [comment]
I submitted https://github.com/kdave/btrfs-progs/pull/181 with the fixes me & another person were working on, but interestingly that file didn't come up. Then again, it wasn't with gcc 9.

**Comment by kdave** [comment]
I've fixed some of the address-of-packed-member calls but the rest seems to be false alert. So the warning option is now off by default but still available under W=1.

The pull request #181 seems to fix different things, so I'll reply there.
