### ISSUE TITLE
restore: symlink failed to chown, bad file descriptor

### ISSUE THREAD

**Issue by pjw91** [kdave/btrfs-progs#183]
When I execute `btrfs restore -S` to restore a symlink, it prints:
```
SYMLINK: 'dest/path/of/symlink' => 'symlink/target'
Failed to change owner: Bad file descriptor
```

And at [cmds-restore.c#L937](https://github.com/kdave/btrfs-progs/blob/f88e48f606528d935de83f393e16f42259437588/cmds-restore.c#L937):
```c
ret = fchownat(-1, file, btrfs_inode_uid(path.nodes[0], inode_item),
                           btrfs_inode_gid(path.nodes[0], inode_item),
                           AT_SYMLINK_NOFOLLOW);
```

I'm not familiar with syscalls, and cannot find the documentation for using -1 as dirfd.
I *think* that the dirfd should be `AT_FDCWD` (which is -100 on Linux 4.15.0-51, Ubuntu 16.04).

**Comment by kdave** [comment]
Yeah -1 is undocumented and probably wrong, AT_FDCWD it should be. There's another -1 in the same function for utimensat.

**Comment by kdave** [comment]
The paths are always absolute, so the dirfd values have no effect, AT_FDCWD is safe and -1 is a bad descriptor. I can't reproduce the issue though.
