### ISSUE TITLE
Clarify what commands work on directories or subvolumes. 

### ISSUE THREAD

**Issue by Gatak** [kdave/btrfs-progs#185]
It would be good if the manual clarified what commands work on full filesystem, subvolumes or directories only. It isn't always very clear or obvious. 
https://github.com/kdave/btrfs-progs/blob/master/Documentation/btrfs-filesystem.asciidoc

`scrub` works on whole filesystem only. 
`defrag -r` works on directories, and does not recurse into subvolumes. 
`du -s` works on directories and also recurse into subvolumes.

Thanks.

**Comment by kdave** [comment]
**Scrub** can work on one device or all devices (default). As I read the btrfs-scrub page I think it's stated clearly. The page btrfs-filesystem says that "there are other whole filesystem operations like scrub [...]" so I don't think it's confusing. In this case I'd appreciate more concrete hints what and where to explain better what do you expect but miss in the documentation.

**Comment by kdave** [comment]
**defrag -r** not descending to subvolumes, you're right about that one. The subvolumes behave similar to mount points and the path traversal code is told not to go to mount points. This is understandable, defrag should not go to other filesystems, but unfortunatelly this also means other potential subvolumes on the same filesystem.

This is fixable though. I'll update the docs about current behaviour and open an issue about extending defrag to also go to subvolumes (a new option).

**Comment by kdave** [comment]
**du -s** is missing the documentation, I'll add it.

**Comment by kdave** [comment]
All sorted, I've added some tests for defrag and du for future reference. Please reopen if you think the  woding in the docs can be improved.

**Comment by Gatak** [comment]
Thanks!
