### ISSUE TITLE
Installation problem on centos7, error message is "no package 'libzstd' found"

### ISSUE THREAD

**Issue by tom-TangT** [kdave/btrfs-progs#195]
![4OQWPL}7YMINJIKE4HK43A5](https://user-images.githubusercontent.com/52006536/62046356-4e1ecf00-b23a-11e9-8abb-7c07a4028da0.png)

**Comment by Lakshmipathi** [comment]
Have you tried something like `yum install libzstd libzstd-devel -y`  If you want to skip this package try something like `disable-zstd`  with `configure`

**Comment by tom-TangT** [comment]
> Have you tried something like `yum install libzstd libzstd-devel -y` If you want to skip this package try something like `disable-zstd` with `configure`

I had tried both 'yum install libzstd 'and 'yum install libzstd'  ,but nothing to contribute.Is it because I put the mirror source on centos？Also, the libreiserfscore download was unsuccessful.
![image](https://user-images.githubusercontent.com/52006536/62048103-9a6c0e00-b23e-11e9-8e25-bd7d2c709900.png)
It shows ‘No software packages available：libreiserfscore’
‘Error, nothong to do’

**Comment by Lakshmipathi** [comment]
Sometime ago this used to work https://github.com/Lakshmipathi/btrfsqa/blob/master/setup/scripts/002_btrfsprogs#L5 fine on centos. May be try enabling centos epel repo  ? or you can get it from source https://github.com/facebook/zstd/releases/ 

I'm not sure about reiserfs dependency. From INSTALL file says its required if you need `btrfs-convert` command on reiserfs source.  May be try 'yum search' for reiserfs devel packages.

**Comment by tom-TangT** [comment]
> Sometime ago this used to work https://github.com/Lakshmipathi/btrfsqa/blob/master/setup/scripts/002_btrfsprogs#L5 fine on centos. May be try enabling centos epel repo ? or you can get it from source https://github.com/facebook/zstd/releases/
> 
> I'm not sure about reiserfs dependency. From INSTALL file says its required if you need `btrfs-convert` command on reiserfs source. May be try 'yum search' for reiserfs devel packages.

Thank you！I will try it！

**Comment by kdave** [comment]
The required version of reiserfs library is probably not distributed everywhere, you can download it from https://www.kernel.org/pub/linux/kernel/people/jeffm/reiserfsprogs/ , and libzstd is at the mentione github link at.
If you don't need the functionality, then `./configure --disable-zstd and --with-convert=ext2`

**Comment by tom-TangT** [comment]
> The required version of reiserfs library is probably not distributed everywhere, you can download it from https://www.kernel.org/pub/linux/kernel/people/jeffm/reiserfsprogs/ , and libzstd is at the mentione github link at.
> If you don't need the functionality, then `./configure --disable-zstd and --with-convert=ext2`

OK，I'm going to try to cancel things that I don't need.
Also, do you know why python3.6.4 is installed but reports an error 'no package 'python3.6' found' when executing './configure'

**Comment by kdave** [comment]
The python bindings are necessary, not just python interpreter. The package name can be eg. `python3-devel`.

**Comment by tom-TangT** [comment]
> The python bindings are necessary, not just python interpreter. The package name can be eg. `python3-devel`.

stupid me! closed!Thank you for your help！
