### ISSUE TITLE
While running tests from testsuite: mkfs  test failed for case 011-rootdir-create-file

### ISSUE THREAD

**Issue by Lakshmipathi** [kdave/btrfs-progs#198]
I did `make testsuite`  to create `tests/btrfs-progs-tests.tar.gz` file. After copying this tar and running it from different system `mkfs` tests fail with below message.

> [TEST/mkfs]   011-rootdir-create-file
failed: /usr/local/bin/mkfs.btrfs -f --rootdir /usr/local/bin/Documentation/ btrfs-progs-mkfs.rootdirVSUlvAy
test failed for case 011-rootdir-create-file

Looks like below testcase assume `Documentation` directory will be always present
```
$cat 011-rootdir-create-file/test.sh
#!/bin/bash
# Regression test for mkfs.btrfs --rootdir on non-existent file.
# Expected behavior: it should create a new file if destination doesn't exist
# Regression 460e93f25754 ("btrfs-progs: mkfs: check the status of file at mkfs")

source "$TEST_TOP/common"

check_prereq mkfs.btrfs

tmp=$(mktemp -d --tmpdir btrfs-progs-mkfs.rootdirXXXXXXX)
# we can't use TEST_DEV, a file is needed
img=$(mktemp btrfs-progs-mkfs.rootdirXXXXXXX)
run_check "$TOP/mkfs.btrfs" -f --rootdir "$TOP/Documentation/" "$img"

rm -rf -- "$img"

```

https://gitlab.com/giis/btrfs-progs/-/jobs/275910761

**Comment by kdave** [comment]
Right, using Documentation was a lazy solution, we need some data generator instead.

**Comment by marcosps** [comment]
@Lakshmipathi I believe that bbb3d8f6f0e4c2022153b22411ce64608c64b5c2 fixed this issue. I tested here and it worked as expected.
