### ISSUE TITLE
how to restore a snapshot without snapper?

### ISSUE THREAD

**Issue by tom-TangT** [kdave/btrfs-progs#199]
I had created a snapshot but i don't know how to restore it.I just can open it and see the information which brfore snapshot.

**Comment by kdave** [comment]
Can you please be more specific? How did you create the snapshot, where, what do you mean by restore. You may better ask for help at the `snapper` project as `btrfs-progs`'s goal is to provide basic functionality and support for various user tasks while snapper has a more specific goal.
