### ISSUE TITLE
Doc: scrub: explain unverified 

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#200]
There was a question posted by Bobpaul on wiki, this is a duplicate for tracking purposes.

I'm having troubling finding an explanation for the different error classes in the scrub status output. For example: recently I had a disk drop out during usage. I powered off the system, fixed the connection, and btrfs resumed using the disk. I ran a scrub with -Bd and the disk that had been disconnected showed the following error summary: 

```
Error summary:    verify=68082 csum=9499110
  Corrected:      9567192
  Uncorrectable:  0
  Unverified:     6592400
WARNING: errors detected during scrubbing, corrected
```

Corrected and Uncorrectable are self-explanatory. But what are unverified errors?

**Comment by CyberShadow** [comment]
I found this, does it help?

https://github.com/kdave/btrfs-progs/blob/9a85732d8beaae4b80cab98bb3355660389c1d36/ioctl.h#L143-L146

**Comment by kdave** [comment]
Yeah that's it. I don't know why this was added, it's kind of low-level detail how the data are read. And `unverified` is quite confusing.

**Comment by CyberShadow** [comment]
The relevant kernel code has some more-likely-sounding explanations in a comment:

https://github.com/kdave/btrfs-devel/blob/089cf7f6ecb266b6a4164919a2e69bd2f938374a/fs/btrfs/scrub.c#L950-L957

**Comment by kdave** [comment]
Fixed in devel.
