### ISSUE TITLE
rescue: add new command to create control device

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#223]
Add new command `btrfs rescue create-control-device` that will create `/dev/btrfs-control` node (see 'CONTROL DEVICE' in btrfs(5)). This is just for convenience in case the `mknod` utility is not available for some reason, that's why it's in the 'rescue' group too.

**Comment by danobi** [comment]
Patchset up here: https://lore.kernel.org/linux-btrfs/cover.1604013169.git.dxu@dxuuu.xyz/T/#t

**Comment by kdave** [comment]
Pushed to devel.

**Comment by BarryHuffman** [comment]
This was a great idea as mknod has the potential to be inconsistent for example coreutils `mknod --help` even states: 

> NOTE: your shell may have its own version of mknod, which usually supersedes
> the version described here.  Please refer to your shell's documentation
> for details about the options it supports.

**Comment by kdave** [comment]
I did not know that, thanks. The usecase for the command is quite narrow but at least it would behave consistently when needed.
