### ISSUE TITLE
dduper: "No such file or directory" on broken links

### ISSUE THREAD

**Issue by berryamin** [kdave/btrfs-progs#240]
Namaste !

  thank you for dduper,  looks like dduper does not handle broken links properly yet, here is what I get;

I tried to use it, ,but had no success with broken symlinks. Here is my report;

kalou@myvps:~/btrfs-progs$ df -h .
Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/data-home  6.0G  4.4G  1.1G  81% /home

kalou@myvps:~/btrfs-progs$ git remote -v
origin  https://gitlab.collabora.com/laks/btrfs-progs.git (fetch)
origin  https://gitlab.collabora.com/laks/btrfs-progs.git (push)

kalou@myvps:~/btrfs-progs$ git branch -v
* dump_csum 71303187 Update fast-mode option usage

kalou@myvps:~/btrfs-progs$ sudo python dduper --device=/dev/mapper/data-home  --dir=/home --recurse

(...)
Skipped /home/ida/xsh/bin/treeps not unique regular files or             file size < 4kb or size < 32768
Skipped /home/ida/xsh/etc/Makefile not unique regular files or             file size < 4kb or size < 32768
Traceback (most recent call last):
  File "dduper", line 330, in <module>
    main(results)
  File "dduper", line 281, in main
    dedupe_dir(results.dir_path, results.dry_run, results.recurse)
  File "dduper", line 264, in dedupe_dir
    if validate_file(fn) is True:
  File "dduper", line 247, in validate_file
    file_stat = os.stat(filename)
OSError: [Errno 2] No such file or directory: '/home/ida/xsh/etc/icecast.xml'

(this issue was fatal, and program stopped without deduping anything)

kalou@myvps:~/btrfs-progs$ df -h .

Filesystem             Size  Used Avail Use% Mounted on
/dev/mapper/data-home  6.0G  4.4G  1.1G  81% /home

root@myvps:~/btrfs-progs$ ls -l /home/ida/xsh/etc/icecast.xml
lrwxrwxrwx 1 ida ida 24 Dec 31 10:33 /home/ida/xsh/etc/icecast.xml -> ../Local/etc/icecast.xml

root@myvps:/home/ida/xsh/etc# ls -ltr icecast.xml
lrwxrwxrwx 1 ida ida 24 Dec 31 10:33 icecast.xml -> ../Local/etc/icecast.xml

root@myvps:/home/ida/xsh/etc# ls ../Local
ls: cannot access '../Local': No such file or directory

kalou@myvps:~/btrfs-progs$ uname -a
Linux myvps 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

**Comment by Lakshmipathi** [comment]
Hello @berryamin. 

oops, sorry just found that `issues` missing on https://github.com/Lakshmipathi/btrfs-progs. Enabled it, reposted this issue and tagged you there. thanks! 

@kdave, please close this issue since these patches not on  official `btrfs-progs`

**Comment by kdave** [comment]
Ok.
