### ISSUE TITLE
btrfs-progs v5.6 [TEST/mkfs] 018-multidevice-overflow on ppc32

### ISSUE THREAD

**Issue by ernsteiswuerfel** [kdave/btrfs-progs#241]
Tests were run on kernel 5.6.2. make tests reports
```
    [TEST/mkfs]   018-multidevice-overflow
truncate -s 6E failed: 1
test failed for case 018-multidevice-overflow
```
[mkfs-tests-results.txt](https://github.com/kdave/btrfs-progs/files/4446056/mkfs-tests-results.txt)

Probably the fix of #192  has not landed in master yet?

**Comment by marcosps** [comment]
@ernsteiswuerfel I'll resent the patch. I sent multiple versions of the same fix, and a previous one was merged (which does not skips the test). I hope to have this merged this week in devel branch.

**Comment by marcosps** [comment]
@ernsteiswuerfel can you try the patch above on top of current devel? If it works I'll resend this patch to ML and add your Tested-by tag, if you allow me (I would need your name and email to tag you correctly :) )

**Comment by ernsteiswuerfel** [comment]
Thanks! With your patch -devel works again.
```
# TEST=018\* ./mkfs-tests.sh
    [TEST/mkfs]   018-multidevice-overflow
    [NOTRUN] Current kernel could not create a 6E file
```
No prob. I'll send you an email with my data.

**Comment by kdave** [comment]
Fix is now in devel, thanks.
