### ISSUE TITLE
nodatacow/nodatasum = no compression?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [kdave/btrfs-progs#246]
Hello, I don't know where to post this so I decided to post it here.

I don't understand in https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs(5)#MOUNT_OPTIONS, where it says: 
```
    Note: If nodatacow or nodatasum are enabled, compression is disabled.
```
If I have the `nodatacow,compress=lzo,space_cache=v2,relatime,nossd` mount options , then will `compress=lzo` be redundant?

**Comment by kdave** [comment]
No problem asking here, if the documentation is not clear enough then it's an issue and should be fixed.

The mount options have some constraints, like nodatacow and compression, and the options are processed in order, the last overrides effects of the previous. So, if there's nodatacow, followed by compress, then nodatacow is dropped. If it was the other way around, then compression will be disabled and nodatacow would be in effect.

The system log is verbose about that, `mount -o nodatacow,compress=lzo`:
```
[262832.405058] BTRFS info (device sdc15): setting nodatacow, compression disabled
[262832.424624] BTRFS info (device sdc15): use lzo compression, level 0
```
It does not explicitly say that nodatacow is dropped, I'm not sure if it should be that specific. To see which mount options have been actually applied, the output of `mount` will tell you:
```
/dev/sdc15 on /mnt/test type btrfs (rw,relatime,compress=lzo,space_cache,subvolid=5,subvol=/)
```

**Comment by TheEvilSkeleton** [comment]
It makes sense now. Thank you so much.
