### ISSUE TITLE
Document drawbacks of btrfs-convert in its manpage

### ISSUE THREAD

**Issue by mweinelt** [kdave/btrfs-progs#257]
I joined #btrfs on freenode asking about btrfs-convert and was immediately discouraged because of several drawbacks attached to it. Instead I was recommended to `mkfs` instead.

These drawbacks are unfortunately not part of the manpage at https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-convert, so I didn't know of them until I asked.

**If** they are in the man page I missed them. Then I'd recommend creating a dedicated section to highlight them.

CC @Zygo @knorrie

**Comment by adam900710** [comment]
Mind to share the drawbacks?

I know that the chunk layout is not optimized, but it shouldn't cause obvious problem if the user chooses to balance with the image subvolume deleted.

**Comment by mweinelt** [comment]
One of the issues mentioned was that few people are actually using or testing this. But for more details I'd have to defer to the people mentioned in the original post.

**Comment by adam900710** [comment]
Well, at least that less tested point is completely valid.

**Comment by kdave** [comment]
Documentation updated.
