### ISSUE TITLE
"mkfs.btrfs --data dup" fails when "--rootdir" source directory is larger than ~100M in size

### ISSUE THREAD

**Issue by c-to-the-l** [kdave/btrfs-progs#258]
# Error Description

When using `mkfs.btrfs` with the `--data dup` and `--rootdir` options, `rootdir` directories larger than approximately 80M will cause creation to fail. Smaller-sized directories appear to work as expected.

```
$ mkdir rootdir
$ head -c 100M /dev/urandom > rootdir/somefile
$ mkfs.btrfs --data dup --rootdir rootdir fs.btrfs
btrfs-progs v5.6.1
See http://btrfs.wiki.kernel.org for more information.

Unable to find block group for 0
Unable to find block group for 0
Unable to find block group for 0
ERROR: unable to add file items for somefile: -28
ERROR: unable to traverse directory rootdir: 1
ERROR: error while filling filesystem: 1
$
```
Reducing directory size "fixes" (avoids) the issue (continued from previous logs) - 

```
$ rm fs.btrfs
$ head -c 50M /dev/urandom > rootdir/somefile
$ mkfs.btrfs --data dup --rootdir rootdir fs.btrfs
btrfs-progs v5.6.1
See http://btrfs.wiki.kernel.org for more information.

Making image is completed.
Label:              (null)
UUID:               8cf13208-87c1-4299-a840-f34824dbe531
Node size:          16384
Sector size:        4096
Filesystem size:    229.00MiB
Block group profiles:
  Data:             DUP              84.00MiB
  Metadata:         DUP              32.00MiB
  System:           DUP               8.00MiB
SSD detected:       no
Incompat features:  extref, skinny-metadata
Checksum:           crc32c
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1   229.00MiB  fs.btrfs
$
```

This bug only appears to happen with the `--data dup` profile, although other modes (other than the default) haven't been thoroughly tested.

Platform is x86, Manjaro specifically. 

For readability I used the package manager's version of `mkfs.btrfs`, but this bug is also present on versions of `btrfs-progs` built from the latest source.

**Comment by adam900710** [comment]
The fs you're creating is only 229MiB sized.

With data DUP, it takes twice the space, with 32M x2 for metadata reserved, there isn't much space left to containing data.

That's why we hit -ENOSPC if the data is too large and your fs is too small.

It doesn't look like a bug, although the error message can definitely be improved.
Or do you want early warning/space check before we really begin to copy data?

**Comment by c-to-the-l** [comment]
I'm not sure I understand, I'm not specifying a filesystem size with `--byte-count`, so why would it be hitting a limit? Is the created image not automatically sized to the data, equivalent to `--shrink`?

**Comment by c-to-the-l** [comment]
After testing further, I can improve the behaviour by specifying progressively larger and larger filesystem sizes, but there's some numerical aspect which doesn't strictly make sense to me -

For a source directory size of 400M, creating a filesystem **without** `--data dup` succeeds , where `--byte-count` can be anything down to `600M` (understandable overhead for metadata) - 

```
$ rm fs.btrfs
$ du -sh rootdir
401M    rootdir
$ mkfs.btrfs -b 600M --rootdir rootdir fs.btrfs
btrfs-progs v5.6.1
See http://btrfs.wiki.kernel.org for more information.

Making image is completed.
Label:              (null)
UUID:               33674c93-3035-4352-b93f-2645f13ae8a6
Node size:          16384
Sector size:        4096
Filesystem size:    600.00MiB
Block group profiles:
  Data:             single          512.00MiB
  Metadata:         DUP              32.00MiB
  System:           DUP               8.00MiB
SSD detected:       no
Incompat features:  extref, skinny-metadata
Checksum:           crc32c
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1   600.00MiB  fs.btrfs

$
```

However with `--data dup`, it appears to require a **minimum** `--byte-count` of **8G** before it will create the filesystem, which (to me) seems far too large - 

```
$ rm fs.btrfs
$ mkfs.btrfs --byte-count 7G --data dup --rootdir rootdir fs.btrfs
btrfs-progs v5.6.1
See http://btrfs.wiki.kernel.org for more information.

Unable to find block group for 0
Unable to find block group for 0
Unable to find block group for 0
ERROR: unable to add file items for somefile: -28
ERROR: unable to traverse directory rootdir: 1
ERROR: error while filling filesystem: 1
$ rm fs.btrfs
$ mkfs.btrfs --byte-count 8G --data dup --rootdir rootdir fs.btrfs
btrfs-progs v5.6.1
See http://btrfs.wiki.kernel.org for more information.

Making image is completed.
Label:              (null)
UUID:               df5ace08-faa5-4cd8-a7f6-007401ff73f3
Node size:          16384
Sector size:        4096
Filesystem size:    8.00GiB
Block group profiles:
  Data:             DUP             593.56MiB
  Metadata:         DUP             256.00MiB
  System:           DUP               8.00MiB
SSD detected:       no
Incompat features:  extref, skinny-metadata
Checksum:           crc32c
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1     8.00GiB  fs.btrfs

$
```

Additionally, passing `--shrink` will shrink the final filesystem to well below the "minimum" as imposed at filesystem creation time. From the example above, adding `--shrink` to the `mkfs` call will shrink the final filesystem to ~1.6G, despite 2G not being a "valid" size to pass to `--byte-count`.

(apologies for the wall of logs)

**Comment by adam900710** [comment]
Great! Now the 400M DUP data vs 7G devices size is a pretty good indicator of something went wrong in the rootdir filling option.

Will look into the case.

Thanks for your detailed reporting!

**Comment by adam900710** [comment]
Mind to test if the branch https://github.com/adam900710/btrfs-progs/tree/rootdir_size solves your bug?

It works pretty well locally, but more test won't hurt.

**Comment by c-to-the-l** [comment]
Looks like it works - here's the log (used package manager's tool first, fails test, followed by your branch, succeeds)

```
 $ du -sh rootdir/
401M	rootdir/
 $ mkfs.btrfs --data dup -r rootdir -f rootfs.btrfs
btrfs-progs v5.6.1 
See http://btrfs.wiki.kernel.org for more information.

Unable to find block group for 0
Unable to find block group for 0
Unable to find block group for 0
ERROR: unable to add file items for somefile: -28
ERROR: unable to traverse directory rootdir: 1
ERROR: error while filling filesystem: 1
 $ ./mkfs.btrfs --data dup -r rootdir -f rootfs.btrfs
btrfs-progs v5.6.1 
See http://btrfs.wiki.kernel.org for more information.

ERROR: superblock magic doesn't match
Making image is completed.
Label:              (null)
UUID:               ce510f17-5ff3-44d7-99e0-a5b39be7a699
Node size:          16384
Sector size:        4096
Filesystem size:    1.04GiB
Block group profiles:
  Data:             DUP             448.00MiB
  Metadata:         DUP              53.00MiB
  System:           DUP               8.00MiB
SSD detected:       no
Incompat features:  extref, skinny-metadata
Checksum:           crc32c
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1     1.04GiB  rootfs.btrfs
 $
```
