### ISSUE TITLE
pythons2->python3 update needed for btrfs-debugfs show-blocks

### ISSUE THREAD

**Issue by cmurf** [kdave/btrfs-progs#261]
The btrfs-debugfs show-blocks scripts included in btrfs-progs fail with python3.

Either they should be updated for python3 if they're still useful, or deprecated.

**Comment by Lakshmipathi** [comment]
I think its a nice little script, let me check the issue with python3.

**Comment by Lakshmipathi** [comment]
I did a quick fix. Could you please check this https://github.com/Lakshmipathi/btrfs-progs/commit/bb258fc2206451b133758aaf49ca5388748c3e41

**Comment by kdave** [comment]
I've applied the commit to devel, thanks.

**Comment by Lakshmipathi** [comment]
@kdave Sorry I missed to update the latest patch link. Its https://github.com/Lakshmipathi/btrfs-progs/commit/40a1a573ee7882ee501bc0ab46ffdb3fe51fb55c  could you please use this patch or should I send the patch to mailing-list? Couple of issues caught by @zabbo  https://github.com/Lakshmipathi/btrfs-progs/commit/bb258fc2206451b133758aaf49ca5388748c3e41#commitcomment-40074172 and tested by @cmurf thanks!

**Comment by kdave** [comment]
Ok thanks, I'll update patch for final 5.7.

**Comment by kdave** [comment]
Updated in devel.
