### ISSUE TITLE
mkfs.btrfs shouldn't always use data profile 'raid0' by default with multiple devices

### ISSUE THREAD

**Issue by cmurf** [kdave/btrfs-progs#270]
```
# uname -r
5.8.0-0.rc3.20200701git7c30b859a947.1.fc33.x86_64
# btrfs --version
btrfs-progs v5.7
```

mkfs.btrfs defaults to data profile 'raid0' even when the devices are completely unlike size. 
(a) mkfs.btrfs should use some threshold, maybe 5% difference, by default. If the difference is less than threshold, use 'raid0'. If more than threshold, use 'single'.
(b) mkfs.btrfs should use 'single' profile by default.

The current behavior makes it way too easy (as in, by default) to run into the following two bugs:
https://github.com/kdave/btrfs-progs/issues/269
https://bugzilla.redhat.com/show_bug.cgi?id=1855174

**Comment by kdave** [comment]
Yeah, I agree, raid0 was bad choice for a default. For multiple devices there are also multiple choices about the striping and parity so I guess most users set that explicitly, but the defaults should be something sane anyway. It's much easier to convert from single than from raid0.

**Comment by kdave** [comment]
Changes to defaults need to be done at major releases, I'm tagging this for 5.8.

**Comment by cmurf** [comment]
Related downstream bug has been accepted as release blocking for beta. Ideally a fix lands by Aug 25.
https://bugzilla.redhat.com/show_bug.cgi?id=1855174#c19

**Comment by kdave** [comment]
Pushed to devel. The 5.8 is roughly scheduled to kernel 5.8 release (maybe 2 weeks from now).
