### ISSUE TITLE
subvolume delete: warn if default subvolume is being deleted

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#274]
Kernel will not allow to delete default subvolume, we can detect it at subvolume time and warn as the syslog message might not be noticed. The deletion should not continue, though this would race against concurrent change to the default, but this is highly unlikely and user can simply restart the deletion.

**Comment by realwakka** [comment]
@kdave ,
If there is no one that handle this, is it okay to handle it?

**Comment by kdave** [comment]
Yes, thank you.

**Comment by realwakka** [comment]
@kdave 
Thank you, I've submitted a patch for this.
https://patchwork.kernel.org/patch/11803941/

**Comment by kdave** [comment]
Added to devel, thanks.
