### ISSUE TITLE
Balance seems to be stuck writing 

### ISSUE THREAD

**Issue by MasterCATZ** [kdave/btrfs-progs#279]
![Screenshot from 2020-07-28 06-42-07](https://user-images.githubusercontent.com/1857824/88590157-96ffa280-d09d-11ea-8f42-6e63def96541.png)

I ran out of space on / 

so I turned a 2 gig emergancy file into 0 byte file 
dd  if=/dev/zero of=/freespacefile bs=1 count=1
and removed a heap of old snapper snapshots and was running balance to free up space 

sudo btrfs bal start /.snapshots

how ever instead of just balancing the operating systems file system it also started balancing all btrfs mounted disks
I started the cancle a few weeks ago and it is still doing heaps of writing not noticing any reading 

  TID  PRIO  USER      0.00 BAD  DISK WRITE  SWAPIN     IO171.47OMMAND                                                             
 685934 be/4 root        0.00 B/s  222.76 M/s  0.00 % 64.55 171.40s bal start /.snapshots

sudo btrfs fi balance cancel /

sudo btrfs balance status /
Balance on '/' is running, cancel requested
0 out of about 69 chunks balanced (1 considered), 100% left

apart from unmounting my other btrfs file systems how can I balance / while excluding all other btrfs mount paths ? 

should I force balance to stop / pause ? 

/ is on a MDADM LVM with Btrfs file system

**Comment by MasterCATZ** [comment]
anything I can do to help find the issue ?

should I try rebooting ?

**Comment by automorphism88** [comment]
No idea what's causing the underlying issue, except that `/.snapshots` would in most setups (e.g. snapper) be on the same filesystem as `/` despite being a different subvolume, so it would be expected that you would have started a balance on `/` with the command you gave. Balances are filesystem-wide, regardless of which subvolume's mountpoint you specify, and AFAIK there's no way to balance only a subvolume.

When you cancel a balance, it will finish the chunk that it's working on before stopping, and that can sometimes take a long time (for instance, having lots of snapshots/reflinks, having qgroups enabled, or especially both, will make balances take forever). If you do have quotas enabled, you can disable them mid-balance, and that should expedite things substantially. Quotas + snapshots are the only reason I'm aware of for a balance to take that long.

If you reboot with a balance in progress, it will ordinarily just resume where it left off as soon as the filesystem is mounted. However, you can prevent that from happening by using the mount option `skip_balance` (either via fstab or by editing the kernel command line in your bootloader to add `rootflags=skip_balance`). That is the only way I am aware of to cancel a balance before it finishes the current chunk, and it should be safe to do so.

**Comment by Zygo** [comment]
This is the runaway balance bug.  Upgrade the kernel to 5.4.54 or 5.7.11 or later.
