### ISSUE TITLE
No libbtrfsutil.pc file

### ISSUE THREAD

**Issue by ivzhh** [kdave/btrfs-progs#285]
Hi,

I find that `libbtrfsutil` doesn't have a corresponding `libbtrfsutil.pc` file. I am writing a go binding for `libbtrfsutil` and it is much easier to use pkg-config with cgo. Is it ok to contribute a pc file like:

```pc
prefix=@prefix@
exec_prefix=@exec_prefix@
libdir=@libdir@
includedir=@includedir@

Name: libbtrfsutil
Description: libbtrfsutil library
Version: @BTRFS_UTIL_VERSION_MAJOR@.@BTRFS_UTIL_VERSION_MINOR@.@BTRFS_UTIL_VERSION_PATCH@
URL: http://btrfs.wiki.kernel.org
Cflags: -I${includedir}
Libs: -L${libdir} -lbtrfsutil
```

Thank you!

**Comment by kdave** [comment]
Merged to devel with some changes, thanks.
