### ISSUE TITLE
Add json output for btrfs device stats /

### ISSUE THREAD

**Issue by jelly** [kdave/btrfs-progs#291]
It would be nice to have json output for btrfs device stats so prometheus textcollector's can easily collect device statuses without having to parse the text output as in:

https://github.com/prometheus-community/node-exporter-textfile-collector-scripts/blob/master/btrfs_stats.py#L46

**Comment by realwakka** [comment]
I posted a patch for this issue.
https://patchwork.kernel.org/patch/11781789/

**Comment by kdave** [comment]
The patch needs to be reworked, reply sent to the mailinglist, this issue is still open.

**Comment by realwakka** [comment]
@kdave I submitted a new patch v2 for this. Could you review it?
https://patchwork.kernel.org/patch/11815619/

**Comment by kdave** [comment]
Released in v5.10.
