### ISSUE TITLE
ship udev rules for btrfs raid - extra attributes

### ISSUE THREAD

**Issue by tbzatek** [kdave/btrfs-progs#302]
Somewhat related to #264 that is mostly about mounting degraded volumes, though this one is about IDs provided by `udev` rules.

It would be nice if there were any `udev` attributes uniquely identifying btrfs raid members without a need to mount or assemble the volume first. The current state where `ID_FS_TYPE=btrfs` and `ID_FS_USAGE=filesystem` attributes are present on all btrfs raid components is misleading. Knowing the filesystem structure prior to mounting or calling any external commands (that may not be always present in the system or e.g. in initramfs) would be a great advantage when presenting the overall block device structure to the user.

Looking at `64-btrfs.rules` that is a part of the `udev` package I see a call to the `btrfs` command to set the `ID_BTRFS_READY` attribute. Exposing further information could be done in a similar matter.

**Comment by cmurf** [comment]
Example: A three device Btrfs, udev will list the same ID_FS_UUID three times, with a unique ID_FS_UUID_SUB for each device. The btrfs super block has a num_devices field, but off hand I don't see it exposed/available in udevadm info output.

chart of equivalent attributes:
```
btrfs super     udev              blkid
fsid            ID_FS_UUID        UUID
dev_item.uuid   ID_FS_UUID_SUB    UUID_SUB
```
Is ID_FS_USAGE=other more descriptive? That's the only alternative value I'm seeing for ID_FS_USAGE.

There's definitely some btrfs jargon that seems to be reused and thus familiar But actually there are some meaningful differences. Raid is one of those. Btrfs doesn't do block device level raid, so there is nothing in the superblock that indicates anything more than the number of devices that make up a file system. The "raidness" is a function of each block group, which is a range of extents. I've found these developer docs useful.
https://github.com/btrfs/btrfs-dev-docs/

**Comment by tbzatek** [comment]
> Example: A three device Btrfs, udev will list the same ID_FS_UUID three times, with a unique ID_FS_UUID_SUB for each device. The btrfs super block has a num_devices field, but off hand I don't see it exposed/available in udevadm info output.
> 
> chart of equivalent attributes:
> 
> ```
> btrfs super     udev              blkid
> fsid            ID_FS_UUID        UUID
> dev_item.uuid   ID_FS_UUID_SUB    UUID_SUB
> ```

It's crucial to have both `ID_FS_UUID` and `ID_FS_UUID_SUB` exposed on a non-mounted filesystem as well.

> Is ID_FS_USAGE=other more descriptive? That's the only alternative value I'm seeing for ID_FS_USAGE.

No, not really. `ID_FS_USAGE=filesystem` is still important for existing tools but should be only present on a single/primary block device. In case any change to udev rules will bring this guarantee and would mark the secondary devices as `ID_FS_USAGE=other` it will bring great benefit to userspace. It may possibly break other use cases though.

**Comment by josefbacik** [comment]
What exactly are you looking for from us?  We provide a FS UUID which is unique for the file system, and we provide a device specific UUID which is unique to each device in the file system.  The FS UUID is supposed to be the same between the devices, they are in fact part of the same file system.  If that confuses UDEV then what exactly do you want us to do about it?  I'm not being sarcastic here, I'm honestly asking what we need to provide to make udev happy.  I have 0 insight into UDEV, so a simple "set X value to Y and Z value to A" is all I really need, and then we can work out how to tell udev the right thing.

**Comment by Forza-tng** [comment]
> It would be nice if there were any `udev` attributes uniquely identifying btrfs raid members without a need to mount or assemble the volume first.

All members will have the same FS UUID.

/dev/block/by-uuid/ seems to list filesystems correctly for multi device btrfs - no duplicates are listed.

**Comment by cmurf** [comment]
> It's crucial to have both `ID_FS_UUID` and `ID_FS_UUID_SUB` exposed on a non-mounted filesystem as well.

`udevadm info --export-db` does show both `ID_FS_UUID` and `ID_FS_UUID_SUB` for each btrfs device, without it having been previously mounted. The same information is exposed by libblkid.

**Comment by tbzatek** [comment]
I guess I created slight confusion last time, I've managed to find sufficient runtime information in `/sys/fs/btrfs/` in the meantime. While I'm still evaluating all the required data needed, I guess you can disregard this ticket for the moment. Let me close it once I'm sure nothing else is needed.

**Comment by tbzatek** [comment]
Let's close this for the time being, I'm afraid I wouldn't be able to get back to testing this anytime soon.
