### ISSUE TITLE
RFE: 'btrfs property' compression needs to support value `false`

### ISSUE THREAD

**Issue by cmurf** [kdave/btrfs-progs#308]
An object with compression set to value `""` `no` or `none` has
```
sequence 5 flags 0x8(NOCOMPRESS)
```

Whereas a new file:
```
sequence 3 flags 0x0(none)
```

Need a way to get back to `flags 0x0` by compression value `false`. In particular, once set, it even survives btrfs send/receive. So at the moment it can be difficult to get back to `flags 0x0(none)`

Or maybe make the values the same as the existing flags: 'nocompress' and 'none' and deprecate both `""` and `no` values.

But just adding `false` to mean `flags 0x0(none)` is fairly intuitive, and consistent with existing property `ro`.

**Comment by kdave** [comment]
This has been fixed by kernel commit  torvalds/linux@5548c8c6f55bf0097075b3720e14857e3272429f in 5.15 and in progs 7781d1a2daa6564c3988dc268eb0680e057027f5 in 5.17 .
