### ISSUE TITLE
Confusion over the snapshot section of man(8) btrfs-subvolume

### ISSUE THREAD

**Issue by parke** [kdave/btrfs-progs#316]
I believe it would be an improvement to rewrite the snapshot section of man(8) btrfs-subvolume as follows:

```
snapshot [-r|-i <qgroupid>] <source> <dest>

Create a snapshot of the subvolume <source>.

If <dest> does not exist, then the snapshot will be created at <dest>.

If <dest> already exists and is a directory, then the snapshot
will be created inside <dest>.  The name of the snapshot will
be the basename of <source>.

If <source> is not a subvolume, btrfs returns an error.
```

I believe the current (IMO confusing) version is here:
https://github.com/kdave/btrfs-progs/blob/devel/Documentation/btrfs-subvolume.asciidoc

If desired, I would be happy to prepare a pull request.

See also this related issue:
https://github.com/kdave/btrfs-progs/issues/76

**Comment by kdave** [comment]
This was fixed long ago before the conversion from asciidoc to RST.
