### ISSUE TITLE
Core dump, and other weidrness `subvolume show -u|r`

### ISSUE THREAD

**Issue by moviuro** [kdave/btrfs-progs#317]
```
# btrfs subvolume show --uuid -- / # -- was supposed to be "end of flags"
ERROR: can't find uuid '00000000-0000-0000-0000-000000000000' on '/'
free(): double free detected in tcache 2
[1]    3375976 abort (core dumped)  btrfs subvolume show --uuid -- /
```

Also, the manpage is quite concise about what `btrfs subvolume show -r|u` actually does. I excpected it to return only the subvolume's ID or rootID, because ATM to collect only the UUID, you have to pipe, grep, etc.

```
expected # btrfs subvolume show --uuid -- /
5e076a14-4e42-254d-ac8e-55bebea982d1
```

**Comment by kdave** [comment]
The double free is now fixed in devel. The option --uuid acts as a selector, ie. look for subvolume with the given uuid, not that it will print just the uuid. The help text and the command line argument description is wrong, the argument is required.

**Comment by kdave** [comment]
Now fixed in devel too. The command is supposed to print all the information so you'd still need to use grep etc. The json output could make it easier, once it lands.
