### ISSUE TITLE
btrfs receive is slow and uses a lot of CPU

### ISSUE THREAD

**Issue by klartom** [kdave/btrfs-progs#324]
I'm trying to transfer a large snapshot of more than 40TB to my backup host using the btrfs send and receive mechanism piped through ssh.

Sending host:
Fedora 33
AMD ThreadRipper 1920X - 128GB RAM
2x10GBit Ethernet, bonded
MegaRaid 9270
6x16TB Seagate Exos in RAID5

Receiving host:
Fedora 33
Intel i3-7300 - HT enabled - 32GB RAM
10GBit Ethernet, single connection
MegaRaid 9260
12x8TB WD NAS drives in RAID5

The 2 hosts are connected to the same 10G switch. The sender could definitely saturate a 10GBit link. The practically achievable writes on the backup host would be lower, but still at least 400MB/s. The file system contains mostly large files of 1GB+, so there is little meta-data.

With btrfs send/receive I'm getting a steady transfer rate of 60MB/s. The copy has been running for a little over 5 days now, having only transferred some 25TB. This is way too slow for this setup.

Analyzing resource usage, the sender side is fine, both the btrfs send and the corresponding ssh process only use about 10-10% CPU, which on a 24 threaded machine is virtually nothing. However, the receiver is running with a load of ~2.6, with the sshd using 30-50% CPU and the btrfs receive a further 60-70%. The rest of the load comes from IO wait. So the bottleneck is the btrfs receive clearly.

I have found some hints, that this method of transfer is not at a binary copy, but copies the snapshot with some sort of a transactional logic. Taking a cursory glance at receive.c, this indeed seems to be the case, that files and directories are created, attributes set, etc. I'm no C developer, but it looks like the process_write function writes out individual inodes. Maybe that's the cause, though the process would probably need to be profiled to clearly see why it uses so much CPU time to simply copy data.

I was using ZFS until recently. The same kind of a backup could do about 200MB/s and at that time neither host had a RAID card, both were using software RAID and the backup had only a Celeron CPU. When copying from ZFS to the btrfs, rsync did about 300MB/s.

I don't know if you can or want to do anything about this, but I thought I would share my experiences. In testing a new FS, this kind of a usecase probably doesn't come up that often. For my part, I think I have to return to ZFS, because this extreme inefficiency isn't something I can live with.

**Comment by ivzhh** [comment]
Have you tried to directly dump to a file? What's the performance for that?

```
btrfs send /some/subvol | ssh target 'cat > a.dump'
```

**Comment by ivzhh** [comment]
Here are two `perf record` flamegraphs for [my kernel TLS patch](https://github.com/kdave/btrfs-progs/issues/326):

- `-big`: a subvol with a 8GB file
- `-small`: a subvol with tons of small files

The two computers are connected by 1Gbps network and send-side uses SATA SSD, receive-side uses NVME SSD. The average speed is 110MBps for `-big`. It seems the time is spent on CRC32.

[perf-svg.zip](https://github.com/kdave/btrfs-progs/files/5742697/perf-svg.zip)

**Comment by klartom** [comment]
I have already destroyed the btrfs on the backup host, so my options are now a bit limited, but I have done a bit of further testing with what I have left:

1. On the ThreadRipper host, use btrfs send to write into a file on a local nvme. The result is a steady 400-450MB/s.
2. On the same host, using the same file-system, but reading out a non-cached, random large file. This does a little over 600MB/s

So even the btrfs send is performing worse than actual file reads, but as my original submission has shown, the processing by the btrfs recv makes it much-much worse.

**Comment by ivzhh** [comment]
Thanks for testing! A few things I found on the benchmark, I am not sure if they can ring a bell on your setup:

- I have not implemented a `mbuffer` like feature for TLS. That may help pipelining process. You can try `mbuffer` to rule out network overhead.
- Old checksum: xxhash can be [way faster](https://github.com/kdave/btrfs-progs/blob/2e1fa482300449042ff6612bb51027f3f5765270/crypto/xxhash.h#L42) (`10x` faster in ideal case), if you build a new file system with `mkfs.btrfs`, you can try xxhash.
- Another issue with CRC is the data addresses are not 8 bytes aligned so the faster version is not called (Fedora 33 64 bit).
- I use dm-crypt and it contributes to a non-trivial portion of CPU time.
- `btrfs receive` opens file with `O_RDWR`. File system buffer should work here. So `pwrite` in `process_write` should not block that long (this part is a guess)

**Comment by ivzhh** [comment]
Just bought a new RAM and I did a new benchmark with tmpfs. Here are the steps I follow to do benchmarking and profiling:

- NVME SSD, dm-crypt + btrfs
- Subvol `-big`: a 6.5GB subvol with three large files
- Subvol `-small`: 4.3 GB subvol with Torvalds' Linus git tree, 76k files
- `btrfs send` both subvols into `/tmp/{big,small}.dump` to simulate 10Gbps network
- Use `dd bs=48k count=1k conv=fdatasync` to test ideal writing speed, the result is roughly `650 MiBps`. `48k` is the size of `BTRFS_SEND_C_WRITE` in my case.
- Use Fedora 33's latest btrfs-progs `-orig` and my own btrfs-progs (with [CRC alignment fix on patchwork](https://patchwork.kernel.org/project/linux-btrfs/patch/20201226214606.49241-1-shngmao@gmail.com/)) `-crc`

The goal is to find the potential improvements.

- `-big` + `-orig`: `320 MiBps`
- `-small` + `-orig`: `283 MiBps`
- `-small` + `-crc`: `515 MiBps`

Each number is not an *accurate* statistics from thousands run; only the trend is studied here.

- `-big` is faster than `-small`: `-small` creates more files and performs more `rename`
- `-crc` does improve performance
- There is still room for improvement
- *It can work better than `rsync`*

I still don't have 10Gbps network, so I cannot compare kernel TLS patch with ssh tunnel.

**Comment by kdave** [comment]
Thanks for the report, analysis and the fix. I've copied the interesting parts to the changelog and committed the fix to devel.

**Comment by polarathene** [comment]
> * Old checksum: xxhash can be [way faster](https://github.com/kdave/btrfs-progs/blob/2e1fa482300449042ff6612bb51027f3f5765270/crypto/xxhash.h#L42) (`10x` faster in ideal case), if you build a new file system with `mkfs.btrfs`, you can try xxhash.

Just wanted to point out that I came across [this Fedora discussion](https://pagure.io/fedora-btrfs/project/issue/40#comment-733446) that was about adopting xxhash instead of crc32 due to a misunderstanding of it being faster. Their initial tests turned out to use local hash functions from software, not optimized kernel variants that the filesystem itself uses which could take advantage of HW accel with crc32 which flipped their testing results.

xxhash wasn't anywhere near 10x faster from what I could see though, except for the armv7 and other older architectures where HW instructions were lacking for crc32. Judging by the cited source for the claim, I think it's probably misled as well then from not having performed actual tests with the kernel crypto API implementations on real hardware (_the linked Fedora discussion has a variety of such results shared_).
