### ISSUE TITLE
Cannot build btrfs on Arm 

### ISSUE THREAD

**Issue by mercury131** [kdave/btrfs-progs#325]
Hello!
I can not build btrfs on my NAS with debian 8 with Arm processor. 
autogen.sh and ./configure works fine, but when I run make command , I got this error:
```cmds/inspect.o:(.data.rel.ro+0x3c): undefined reference to `cmd_struct_inspect_dump_csum'
collect2: error: ld returned 1 exit status
Makefile:546: recipe for target 'btrfs' failed
make: *** [btrfs] Error 1```

My system debian 8, kernel 4.4.86 #1 Fri Sep 22 20:41:13 WEST 2017 armv5tel GNU/Linux
What lib it need?

**Comment by kdave** [comment]
That's probably stale build or some 3rd party patch, because `cmd_struct_inspect_dump_csum` is not in current btrfs-progs

**Comment by mercury131** [comment]
Yes, I used this path https://github.com/Lakshmipathi/dduper/blob/master/patch/btrfs-progs-v5.6.1/0001-Print-csum-for-a-given-file-on-stdout.patch . I recheck, everything works fine without it.
Thank you!
