### ISSUE TITLE
btrfs subvolume set-default 0, chooses subvolume other than ID 5

### ISSUE THREAD

**Issue by cmurf** [kdave/btrfs-progs#327]
kernel 5.10.2
btrfs-progs 5.9

Computer 1:
```
$ sudo btrfs sub get /
ID 5 (FS_TREE)
$ sudo btrfs sub set 258 /
$ sudo btrfs sub get /
ID 258 gen 1583489 top level 5 path home
$ sudo btrfs sub set 0 /
$ sudo btrfs sub get /
ID 429 gen 1583483 top level 5 path root
$ 
```

Computer 2:
```
$ sudo btrfs sub get /
ID 5 (FS_TREE)
$ sudo btrfs sub set 285 /
$ sudo btrfs sub get /
ID 285 gen 6979 top level 5 path root
$ sudo btrfs sub set 0 /
$ sudo btrfs sub get /
ID 284 gen 6980 top level 5 path root2old
$ 
```

Setting the default subvolume to 0 should certainly either fail or set it to ID 5. Picking seemingly random (?) subvolid's like this is unexpected.

**Comment by kdave** [comment]
It got broken by converting the set-default to libbtrfsutil in 2116398b1dbe8a4483a64e087c9a4588d8a230d1. Previously the user specified value was passed to kernel, that does the 0->5 fallback, while libbtrfsutil does some path resolution when it sees subvolid 0.

**Comment by kdave** [comment]
Broken since 4.16.

**Comment by kdave** [comment]
So the reason is that 0 is internally used to read the id from the path (`btrfs subvol set-default /subvolume`), but if this is done the other way id + filesystem path, it gets translated to the first case and actually the passed path is resolved and then set as default id.

**Comment by kdave** [comment]
Thanks for the report. Fixed in devel, with a testcase.
