### ISSUE TITLE
Manpage on the Wiki for btrfs-replace is slightly broken

### ISSUE THREAD

**Issue by claell** [kdave/btrfs-progs#330]
https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-replace has some problematic formatting in the [examples section](https://btrfs.wiki.kernel.org/index.php/Manpage/btrfs-replace#EXAMPLES).

Not sure what causes this, as the [original document](https://github.com/kdave/btrfs-progs/blob/devel/Documentation/btrfs-replace.asciidoc) looks good (and also has looked good at the time the Wiki page was last modified). Maybe the lines with `[source,bash]` add colored formatting and then there is some problem with the conversion of those to the Wiki formatting.

**Comment by kdave** [comment]
The manual page documentation has been converted to RST, moved from wiki to https://btrfs.readthedocs.io/en/latest/btrfs-replace.html and the output seems correct now.
