### ISSUE TITLE
Errors while compiling 5.10 - undefined reference to `mnt_table_is_empty'

### ISSUE THREAD

**Issue by ubenmackin** [kdave/btrfs-progs#334]
I'm running a custom CentOS 7 distro, but using a more modern elrepo kernel.

```
# uname -a
Linux rocknas 5.10.10-1.el7.elrepo.x86_64 #1 SMP Sat Jan 23 09:49:22 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
```

Previously, btrfs-progs 5.9 compiled and installed just fine. I noticed that lib mount is now required, so I installed it for my distro:

```
# yum install libmount-devel

===========================================================================================
 Package                      Arch                 Version                       Repository          Size
===========================================================================================
Installing:
 libmount-devel               x86_64               2.23.2-65.el7                 base                82 k
```

However when trying to build btrfs-progs 5.10, I then get the following errors:

```
    [CC]     common/utils.o
common/utils.c: In function ‘find_mount_fsroot’:
common/utils.c:1331:2: warning: implicit declaration of function ‘mnt_table_is_empty’ [-Wimplicit-function-declaration]
  if (!mnt_table_is_empty(tb)) {
  ^
common/utils.c:1339:2: warning: implicit declaration of function ‘mnt_unref_cache’ [-Wimplicit-function-declaration]
  mnt_unref_cache(cache);
  ^
common/utils.c:1343:2: warning: implicit declaration of function ‘mnt_unref_table’ [-Wimplicit-function-declaration]
  mnt_unref_table(tb);
  ^

...

    [LD]     btrfs
libbtrfs.a(utils.o): In function `find_mount_fsroot':
/root/src/btrfs-progs/common/utils.c:1331: undefined reference to `mnt_table_is_empty'
/root/src/btrfs-progs/common/utils.c:1339: undefined reference to `mnt_unref_cache'
/root/src/btrfs-progs/common/utils.c:1343: undefined reference to `mnt_unref_table'
collect2: error: ld returned 1 exit status
make: *** [btrfs] Error 1
```

Could it be the version of libmount I have?

**Comment by ubenmackin** [comment]
To answer my own question, it appears that the functions are a part of lib mount 2.24:

https://github.com/karelzak/util-linux/blob/deba6720fb96951bf81338363eb9e6c2f352ffd3/libmount/src/libmount.sym#L291

**Comment by kdave** [comment]
I evaluated the earliest version of the libmount function and 2.24 is from 2013, that sounded safe enough. However I also want to keep progs working on old enterprise distros and so far am not happy about the libmount dependency. Removing it would require reimplementing the 'mnt_' functions that we need, probably in some upcoming minor release.

**Comment by ubenmackin** [comment]
Thanks for taking a look at this!

**Comment by kdave** [comment]
The devel branch is now libmount-free so that should be back to the pre-5.10 state regarding build dependencies. I haven't tested that in a CentOS 7 environment, I'd appreciate if you could test the build.

**Comment by kdave** [comment]
Verified, builds for me on a CentOS 7 container, so closing.
