### ISSUE TITLE
Run btrfs scrub with mounted filesystem or unmounted block device?

### ISSUE THREAD

**Issue by SampsonF** [kdave/btrfs-progs#335]
https://github.com/kdave/btrfs-progs/blob/master/Documentation/btrfs-scrub.asciidoc

After reading the man page, I got the idea that it can be run against a block device, no matter if the file system is mounted or not.

It turns out scrub can only be run with a mounted filesystem that can be identified by a mount point or a block device.

**Comment by kdave** [comment]
Documentation updated. Please check if it's clear enough for you at https://github.com/kdave/btrfs-progs/blob/devel/Documentation/btrfs-scrub.asciidoc, feel free to suggest more or close the issue. Thanks.
