### ISSUE TITLE
Make test failed on 012-leaf-corruption

### ISSUE THREAD

**Issue by realwakka** [kdave/btrfs-progs#337]
I executed "make test" on current devel branch but it failed at 012-leaf-corruption.
Here is my output.

```
realwakka@realwakka:~/git/btrfs-progs$ sudo make test
    [TEST]   fsck-tests.sh
    [TEST/fsck]   001-bad-file-extent-bytenr
    [TEST/fsck]   002-bad-transid
    [TEST/fsck]   003-shift-offsets
    [TEST/fsck]   004-no-dir-index
    [TEST/fsck]   005-bad-item-offset
    [TEST/fsck]   006-bad-root-items
    [TEST/fsck]   007-bad-offset-snapshots
    [TEST/fsck]   008-bad-dir-index-name
    [TEST/fsck]   009-no-dir-item-or-index
    [TEST/fsck]   010-no-rootdir-inode-item
    [TEST/fsck]   011-no-inode-item
    [TEST/fsck]   012-leaf-corruption
32+0 records in
32+0 records out
32 bytes copied, 0.000127092 s, 252 kB/s
dd if=/dev/zero of=./good.img.restored bs=1 count=32 conv=notrunc seek=4206592
32+0 records in
32+0 records out
32 bytes copied, 0.000125054 s, 256 kB/s
dd if=/dev/zero of=./good.img.restored bs=1 count=32 conv=notrunc seek=20905984
mount -o loop -t btrfs ./good.img.restored -o ro /home/realwakka/git/btrfs-progs/tests/mnt
mount: /home/realwakka/git/btrfs-progs/tests/mnt: wrong fs type, bad option, bad superblock on /dev/loop7, missing codepage or helper program, or other error.
find: '/home/realwakka/git/btrfs-progs/tests/mnt/lost+found': No such file or directory
inode 1862 not recovered correctly
test failed for case 012-leaf-corruption
make: *** [Makefile:420: test-fsck] Error 1
```

I uncommented some code for looking commands executed. 
I think that mounting is failed after corrupting img file.
If I commented the code that corrupting file, It can be mounted correctly.

**Comment by kdave** [comment]
This depends on kernel version, do you use 5.10.x ?

**Comment by realwakka** [comment]
@kdave I used 5.11.0-rc6+ version.

**Comment by realwakka** [comment]
I found some clue. 

I think that kernel commit 3a160a933111241376799244e3587747af574b89 makes this issue.
I revert the commit and the test goes success.

**Comment by mrostecki** [comment]
@realwakka Seems like we are either hitting this condition:

https://github.com/kdave/btrfs-devel/blob/3a160a933111241376799244e3587747af574b89/fs/btrfs/volumes.c#L6875-L6880

or that `dev->disk_total_bytes` is `0` anyway in `verify_one_dev_extent()`

Do you see that `device total_bytes should be at most` in your dmesg? That would indicate the first case.

I will try to reproduce that myself...

**Comment by lorddoskias** [comment]
I think this is fixed by the following commits: https://lore.kernel.org/linux-btrfs/20210326125047.123694-1-wqu@suse.com/
