### ISSUE TITLE
broken device add

### ISSUE THREAD

**Issue by geovex** [kdave/btrfs-progs#339]
btrfs-progs v5.10.1 
```
~# btrfs device add /dev/dm-2 / -f
ERROR: error adding device 'dm-2': No such file or directory
~# btrfs device add /dev/mapper/temp / -f
ERROR: error adding device 'dm-2': No such file or directory
```
however if i use `mknod` in mapper directory and create device node without symlink, i can add device. Is suspect `path_canonicalize` because it has some special treatment for dm devices.

**Comment by kdave** [comment]
I can reproduce it here, thanks for the report. It got broken in 5.10, adding device by the raw /dev/dm-X works on 5.9

**Comment by kdave** [comment]
Fixed in devel.
