### ISSUE TITLE
Consistency. Should "resize" subcommand be moved to the "device" command?

### ISSUE THREAD

**Issue by Forza-tng** [kdave/btrfs-progs#342]
Hi,

I think that the `resize` subcommand should belong in the `btrfs-device` command instead of under the `btrfs-filesystem` command. The reason is that `resize` actually resizes the spaced _allocated on a specific device_, not the filesystem itself. It isn't possible to resize the filesystem without specifying what `device-id` to resize. This is why I'd argue that `resize` should fit in the device command - because we are manipulated how devices are used by btrfs.

```
# btrfs fi sh /mnt/6TB/
Label: '6TB'  uuid: fe0a1142-51ab-4181-b635-adbf9f4ea6e6
        Total devices 3 FS bytes used 7.20TiB
        devid    2 size 2.72TiB used 599.03GiB path /dev/sdc2
        devid    3 size 9.09TiB used 6.92TiB path /dev/sdb2
        devid    4 size 9.09TiB used 6.92TiB path /dev/sde2
```
```
# btrfs filesystem resize -1G /mnt/6TB/
Resize '/mnt/6TB/' of '-1G'
ERROR: unable to resize '/mnt/6TB/': No such device
```
```
# btrfs filesystem resize 2:-1G /mnt/6TB/
Resize '/mnt/6TB/' of '2:-1G'
```

The exception is single devices:
```
# btrfs filesystem resize -4g  /
Resize '/' of '-4g'
```

I'm using btrfs-progs-5.10.1 on kernel-5.10.12

**Comment by kdave** [comment]
It's not a bad idea and can improve usability, the 'id:size' specifiler could be a bit quirky.
