### ISSUE TITLE
btrfs 5.10/5.10.1 compile failure with older kernel-headers

### ISSUE THREAD

**Issue by Dead2** [kdave/btrfs-progs#344]
Hi, not sure whether this is intentional or not, but 5.10 broke compatibility with older kernel headers.

The kernel-headers in use are the current ones from SL/EL/Centos 7 (kernel-headers-3.10.0-1160.15.2.el7).

The commit to blame is b3df561fbf669eb213f9b65ec0782f4bf3afc730

There are multiple problems here, the first is at line `701` referencing an undefined `EXT4_EPOCH_MASK`.
I copied the relevant defines to kerncompat.h, but the next problem was at line `709` missing `i_atime_extra`, so I gave up and just reverted the patch locally.

I could of course solve this by using newer kernel headers, but the internal build system I use currently prevents the installation of newer headers due to other dependencies, so I'd have to package the rpm manually.

**Comment by kdave** [comment]
I'll add a configure-time detection if the symbols are available. If your (or centos 7 in general) e2fsprogs don't support the extra time precision we have no other option than to ifdef around it. Given that the ext4 filesystems would most likely lack the extra time precision as well, it's safe and the build will work.

**Comment by kdave** [comment]
Fixed in devel.
