### ISSUE TITLE
dump-tree line jump artifact

### ISSUE THREAD

**Issue by cmurf** [kdave/btrfs-progs#350]
leaf has a curious artifcact:
```
	item 44 key (167544 XATTR_ITEM 843765919) itemoff 10782 itemsize 54
		location key (0 UNKNOWN.0 0) type XATTR
		transid 436 data_len 8 name_len 16
		name: user.crtime_usec
		data `j
Mм
	item 45 key (167544 XATTR_ITEM 2038346239) itemoff 10677 itemsize 105
		location key (0 UNKNOWN.0 0) type XATTR
		transid 436 data_len 52 name_len 23
		name: system.posix_acl_access
		data 
```

hexdump -C of this leaf 
[hexdumpCofleaf.txt](https://github.com/kdave/btrfs-progs/files/6094078/hexdumpCofleaf.txt)

the problem is here:
```
00002ab0  63 60 6a 0a 4d d0 bc 05  00 02 00 00 00 00 00 00  |c`j.M...........|
```

dump-tree for this leaf
[linejumpartifact-dumptree.txt](https://github.com/kdave/btrfs-progs/files/6094068/linejumpartifact-dumptree.txt)

**Comment by cmurf** [comment]
BTW this inode is a systemd-journald file.

**Comment by kdave** [comment]
The xattr data should be escaped/encoded in some text-friendly way. And filenames probably too.

**Comment by adam900710** [comment]
Agree that xattr data should be escaped.

But don't really believe filenames should be escaped.

Btrfs now is only utilized by Linux, and most if not all Linux uses UTF-8 encoding.
Unless there are some Linux systems using strange encoding like CP936/SJIS for their filenames, escaping filename would just make it less readable for non-ASCII filenames.

**Comment by kdave** [comment]
What about filenames with newlines, terminal control sequences etc.

**Comment by adam900710** [comment]
Is that even possible to add newlines into filenames?

For terminal control sequences, it's indeed something needs to be escaped.

Is there any function/tools to only escape non-char strings?

**Comment by adam900710** [comment]
Or we add some option like --escape=filename,data and let user to choose?

I doubt sane guys would put strange strings into filenames, thus the default would only escape data.

**Comment by kdave** [comment]
For implementation of the encoding there's a new issue #407, I'll keep this one open until it's fixed.

**Comment by kdave** [comment]
Not much point keeping this one open, let's continue in the other issue.

**Comment by kdave** [comment]
Escaped filenames and xattrs will be in 6.10.
