### ISSUE TITLE
btrfs check reports thousands of 'crosses 64K page boudnary, may cause problem for 64K page system'

### ISSUE THREAD

**Issue by cmurf** [kdave/btrfs-progs#354]
btrfs-progs 5.10 used for mkfs
btrfs-progs 5.11 used for btrfs check

Summary: 

Using btrfs check on a file system (with some transid problems) produces over 2600 lines with variations on:
`WARNING: tree block [299024384, 299040768) crosses 64K page boudnary, may cause problem for 64K page system`
These messages only appear with progs 5.11, not 5.10. Either the messages are bogus, or something is wrong with 5.10 mkfs, or 5.11.3 kernel (which was doing all the writes on this file system up until 'the problem' that made me run btrfs check on it.

Also, small typo in the error message: s/boudnary/boundary/

Excessive details:

Used btrfs-progs 5.10 for mkfs, did a Fedora installation using kernel 5.11.3, using qemu-kvm with raw file backing also on Btrfs.
Subsequently something (?) happened to this loop mounted image that results in mount failure:
```
[  252.919659] BTRFS error (device dm-1): parent transid verify failed on 30670848 wanted 185 found 188
```
Complete dmesg of the failure is here, but not directly related to this bug:
https://drive.google.com/file/d/1whDeHGetvuCSgDd8gAFaTlNYOxuGwGXV/view?usp=sharing

Attaching `btrfs check` output for progs 5.10 and 5.11.

[btrfscheck-v5.10.txt](https://github.com/kdave/btrfs-progs/files/6120233/btrfscheck-v5.10.txt)
[btrfscheck-v5.11.txt](https://github.com/kdave/btrfs-progs/files/6120234/btrfscheck-v5.11.txt)

**Comment by cmurf** [comment]
[root@fmac newpool]# btrfs-image -c9 -t4 /dev/mapper/loop0p2 btrfsimage
parent transid verify failed on 30670848 wanted 185 found 188
parent transid verify failed on 30670848 wanted 185 found 188
parent transid verify failed on 30670848 wanted 185 found 188
Ignoring transid failure

btrfsprogsbug354-btrfsimage.bin (19M)
https://drive.google.com/file/d/1OmvC6z-0kPbVe5SDINgxv4-lDcHuld-6/view?usp=sharing

**Comment by adam900710** [comment]
The cross boundary false alert is already fixed in devel branch.

**Comment by kdave** [comment]
Fixed in devel.
