### ISSUE TITLE
btrfs-progs 5.11 warns about RAID5/6 for RAID0

### ISSUE THREAD

**Issue by tavianator** [kdave/btrfs-progs#355]
I'm just trying to balance some low-usage raid0 blocks, but with the new version of btrfs-progs I get

```
# btrfs balance start --bg -dconvert=raid0,profiles=raid0,usage=80 /mnt/neutrino
WARNING:

        RAID5/6 support has known problems and is strongly discouraged
        to be used besides testing or evaluation. It is recommended that
        you use one of the other RAID profiles.
        The operation will continue in 10 seconds.
        Use Ctrl-C to stop.
10 9^C
```

**Comment by tavianator** [comment]
Looking at https://github.com/kdave/btrfs-progs/commit/1ed5db8db445073eb0d8b807901b64edaac1d8c4, it seems that `BTRFS_BALANCE_ARGS_CONVERT` and `BTRFS_BLOCK_GROUP_RAID6` are both `(1ULL << 8)`.  I guess it should be checking `profiles` not `flags`?

**Comment by amstan** [comment]
I see this for raid1 and raid1c3 profiles as well.

**Comment by tavianator** [comment]
Ha hey Alex, been a while!  How's it going?

**Comment by kdave** [comment]
Right, that's broken.

**Comment by kdave** [comment]
> I guess it should be checking `profiles` not `flags`?

`profiles` corresponds to the `profiles=` option, the right one is `flags->target`, as the conversion target bg profile. Fix in devel, with a test.
