### ISSUE TITLE
bogus cache and super generation don't match message

### ISSUE THREAD

**Issue by cmurf** [kdave/btrfs-progs#359]
btrfs-progs 5.11.1

./btrfs check /dev/sdb1 reports:
```
[3/7] checking free space tree
cache and super generation don't match, space cache will be invalidated
[4/7] checking fs roots
```

But the generations are the same.

dump-tree
```
free space tree key (FREE_SPACE_TREE ROOT_ITEM 0) 
leaf 170868736 items 210 free space 10865 generation 189762 owner FREE_SPACE_TREE
```
dump-super
```
generation		189762
```

[btrfscheck.txt](https://github.com/kdave/btrfs-progs/files/6202318/btrfscheck.txt)
[dumpsuper.txt](https://github.com/kdave/btrfs-progs/files/6202320/dumpsuper.txt)
[dumptree.txt](https://github.com/kdave/btrfs-progs/files/6202322/dumptree.txt)

**Comment by cmurf** [comment]
Ahh, it has stale v1 cache I bet...
```
	item 33 key (FREE_SPACE UNTYPED 11841568768) itemoff 9807 itemsize 41
		location key (473 INODE_ITEM 0)
		cache generation 0 entries 0 bitmaps 0
```

**Comment by cmurf** [comment]
```
[chris@fmac btrfs-progs]$ sudo btrfs check --clear-space-cache v1 /dev/sdb1
Opening filesystem to check...
Checking filesystem on /dev/sdb1
UUID: ab845dd9-63b5-4459-b98b-06ed92398247
WARNING: free space cache v2 detected, use --clear-space-cache v2, proceeding with clearing v1
Free space cache cleared
[chris@fmac btrfs-progs]$ 
```
Yep. After that, btrfs check does not complain about generation mismatch. 

It's not exactly a bug then. Feel free to close it

**Comment by cmurf** [comment]
OK it's back. Looks like a mount after clearing v1 cache is causing it.

```
[ 1542.781572] BTRFS info (device sdb1): cleaning free space cache v1
```

After umount and rerunning btrfs check, I get the message again.

This is with both kernel 5.11 and 5.12.

**Comment by Damenly** [comment]
The cache_generation is 0 in dumpsuper.txt. It's a bug of btrfs check.
I just sent the '[PATCH v2] btrfs-progs: check: continue to check space cache if sb cache_generation is 0'  for this.

**Comment by kdave** [comment]
Fixed and released, thanks.
