### ISSUE TITLE
Test misc/015-dump-super-garbage occasionally fails

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#37]
The test fails  due to a bad memory access,

```
(gdb) l
215                             btrfs_chunk_sub_stripes(eb, chunk));
216             for (i = 0 ; i < num_stripes ; i++) {
217                     unsigned char dev_uuid[BTRFS_UUID_SIZE];
218                     char str_dev_uuid[BTRFS_UUID_UNPARSED_SIZE];
219
220                     read_extent_buffer(eb, dev_uuid,
221                             (unsigned long)btrfs_stripe_dev_uuid_nr(chunk, i),
222                             BTRFS_UUID_SIZE);
```

```
#2  read_extent_buffer (eb=eb@entry=0x3630420, dst=dst@entry=0x396f990cfd0, start=start@entry=133980, len=len@entry=16) at extent_io.c:863
863             memcpy(dst, eb->data + start, len);
```

the value of start is out of range, needs to be validated.

**Comment by adam900710** [comment]
It's not hard to fix in print_chunk().

IIRC we need to enhance read_extent_buffer() to validate passed `start` and `len` to really make it bullet proof.

However this will modify the return value type from void to int to indicate error.
This may takes quite some time.

Thanks

**Comment by adam900710** [comment]
Also, backup_root part can also cause problems.

Lu Fengqi and Su yue, along with me will fix them.

Thanks

**Comment by kdave** [comment]
Thanks for the fixes, now in devel.
