### ISSUE TITLE
btrfs-progs v5.12 configure: error: linux/blkzoned.h does not provide blk_zone.capacity

### ISSUE THREAD

**Issue by russdan** [kdave/btrfs-progs#370]
Hi, started `.configure ` of v5.12 to get the following error:

```
.....
checking for REISERFS... yes
checking for FIEMAP_EXTENT_SHARED defined in linux/fiemap.h... yes
checking for EXT4_EPOCH_MASK defined in ext2fs/ext2_fs.h... yes
checking linux/blkzoned.h usability... yes
checking linux/blkzoned.h presence... yes
checking for linux/blkzoned.h... yes
checking for struct blk_zone.capacity... no
checking for BLKGETZONESZ defined in linux/blkzoned.h... no
configure: error: linux/blkzoned.h does not provide blk_zone.capacity
```

OS: Debian 10.9, kernel 5.10.0-0.bpo.5-amd64 (with headers).

Checking  `/usr/include/linux/blkzoned.h`  no `BLKGETZONESZ` present, however `/usr/src/linux-headers-5.10.0-0.bpo.5-common/include/uapi/linux/blkzoned.h` does contain it, so renamed `/usr/include/linux/blkzoned.h` and created a symlink to `/usr/src/linux-headers-5.10.0-0.bpo.5-common/include/uapi/linux/blkzoned.h` and `.configure` now completes successfully.

Not sure what's needed which might help others if they hit the same issue?

**Comment by kdave** [comment]
The system headers are taken from /usr/include and may be packaged separately from kernel sources (on openSUSE it's called linux-glibc-devel, so look for something similar on debian). The 'capacity' member is present since 5.10 so at least this version needs to be installed.

**Comment by kdave** [comment]
It's 'linux-libc-dev' and is 5.10.x on sid, so this should be sufficient. https://packages.debian.org/sid/linux-libc-dev

**Comment by kdave** [comment]
Now documented in INSTALL, closing.
