### ISSUE TITLE
Running `btrfs device scan` on an older kernel fails due to BLKGETZONESZ ioctl

### ISSUE THREAD

**Issue by ericonr** [kdave/btrfs-progs#376]
Hi!

I recently merged an update to `btrfs-progs` version 5.12.1 in Void Linux, but we almost immediately received a bug report (https://github.com/void-linux/void-packages/issues/31275) about an issue with kernel 4.19 (probably happens on older ones as well - we support all LTS kernel releases).

It linked to the following piece of code, which gets triggered when we run `btrfs device scan` in the boot up path:

https://github.com/kdave/btrfs-progs/blob/b16b0a766f06138de2ee32d4d84b7110e469ff49/kernel-shared/zoned.c#L489-L494

I captured an strace locally:

```
stat("/dev/sda2", {st_mode=S_IFBLK|0660, st_rdev=makedev(0x8, 0x2), ...}) = 0
open("/dev/sda2", O_RDONLY)             = 3
fstat(3, {st_mode=S_IFBLK|0660, st_rdev=makedev(0x8, 0x2), ...}) = 0
ioctl(3, BLKGETZONESZ, 0x7ffd8bc0b614)  = -1 ENOTTY (Not a tty)
```

and I assume the `ENOTTY` error was due to the 4.19 kernel not implementing the ioctl. Our current boot path expects `btrfs device scan` to be successful, and launches an emergency shell otherwise, and it would be nice to avoid this situation.

- is modern `btrfs-progs` expected to still work with older LTS kernels? if not, should we just recommend users not use btrfs and old kernels or instead package multiple versions of `btrfs-progs`?
- should a failure in `btrfs device scan` not be considered a "bad sign"?

If this can be solved in code, and you want to point me at the recommended solution, I'd be glad to try my hand at implementing it.

Thanks!

**Comment by kdave** [comment]
> is modern btrfs-progs expected to still work with older LTS kernels? if not, should we just recommend users not use btrfs and old kernels or instead package multiple versions of btrfs-progs?

Yes, old kernels and old build environment compatibility is maintained, using most recent progs should always work because of additional fixes or updates.

> should a failure in btrfs device scan not be considered a "bad sign"?

It should not be considered a hard failure, though some reasons could be significant.

**Comment by kdave** [comment]
Failing when an ioctl is not available is a bug, it should at least check for ENOTTY and other errors. There are more ioctls related to zoned support, eg. BLKREPORTZONE, so that needs to be handled as well.

**Comment by kdave** [comment]
Fixed in devel, I haven't tested it on an old kernel though. For a quick test you can run as root 'btrfs device scan' and it should return with 0.

**Comment by ericonr** [comment]
I should be able to test it soonish, will let you know. Thanks!

**Comment by ericonr** [comment]
@kdave sorry for the delay, but I have now confirmed that it is working with your patch! Will backport into our package so users can take advantage of the 5.12 features.

**Comment by ericonr** [comment]
Would you like to leave this open while 5.12.2 isn't released?

**Comment by kdave** [comment]
Thanks for the test. The release 5.12 will be skipped so it's 5.13 in a few days.
