### ISSUE TITLE
Qgroups via libbtrfs?

### ISSUE THREAD

**Issue by sargun** [kdave/btrfs-progs#38]
Any reason why qgroup.h, and qgroup.o aren't exposed as part of libbtrfs?

**Comment by kdave** [comment]
It's an internal header. And the whole situation with libbtrfs is unsettled. The interface is not clean (namespace, definitions etc), does not cover whole lot of btrfs capabilities. Adding simple bits here and there would just continue the bad trend so I'm not fond of any extensions at the moment.
The raw ioctl interface is usable, but may be a bit tedious to use.
