### ISSUE TITLE
'replace' and 'device add' should issue block discard

### ISSUE THREAD

**Issue by Forza-tng** [kdave/btrfs-progs#390]
I was testing _replace_ and _device add_ in a VirtualBox session and noticed that they do not issue any block discard. I think it should be an option to do so, just as mkfs.btrfs does.

However, they may do so, but it is not working in my test environment. When I try mkfs.btrfs /dev/sde in VBox I don't see any discards either, even though `blkdiscard` works.
```
# mkfs.btrfs -L test /dev/sde
btrfs-progs v5.13.1
See http://btrfs.wiki.kernel.org for more information.

Detected a SSD, turning off metadata duplication.  Mkfs with -m dup if you want to force metadata duplication.
Label:              test
UUID:               2a9ddbba-6f84-4f1d-a002-8d47ca5c9977
Node size:          16384
Sector size:        4096
Filesystem size:    8.00GiB
Block group profiles:
  Data:             single            8.00MiB
  Metadata:         single            8.00MiB
  System:           single            4.00MiB
SSD detected:       yes
Zoned device:       no
Incompat features:  extref, skinny-metadata
Runtime features:
Checksum:           crc32c
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1     8.00GiB  /dev/sde
```
VirtualBox would normally shrink the VDI file when discards are sent. It did not.
`Gentoo OpenRC_4.vdi` is still 3GiB

```
# wipefs -a /dev/sde
/dev/sde: 8 bytes were erased at offset 0x00010040 (btrfs): 5f 42 48 52 66 53 5f 4d

# blkdiscard /dev/sde -v
/dev/sde: Discarded 8589934592 bytes from the offset 0
```
`Gentoo OpenRC_4.vdi` is now only 2MiB.

Just for brevity. `fstrim` works on mounted btrfs filesystem insite VBox.
```
# mount /dev/sde /mnt/btrfs-test/
# fstrim -v /mnt/btrfs-test
/mnt/btrfs-test: 8 GiB (8588754944 bytes) trimmed
```

btrfs-progs: v5.13.1
Kernel: 5.13.4

**Comment by Forza-tng** [comment]
```
 # grep . /sys/block/sde/* 
/sys/block/sde/alignment_offset:0
/sys/block/sde/capability:50
/sys/block/sde/dev:8:64
/sys/block/sde/discard_alignment:0
/sys/block/sde/events_poll_msecs:-1
/sys/block/sde/ext_range:256
/sys/block/sde/hidden:0
/sys/block/sde/inflight:       0        0
/sys/block/sde/range:16
/sys/block/sde/removable:0
/sys/block/sde/ro:0
/sys/block/sde/size:16777216
/sys/block/sde/stat:    3430        0   166014      581    11617   752800 21302000   543238        0    39340   658282       59        5 134204928   112668      150     1793
/sys/block/sde/uevent:MAJOR=8
/sys/block/sde/uevent:MINOR=64
/sys/block/sde/uevent:DEVNAME=sde
/sys/block/sde/uevent:DEVTYPE=disk
```

**Comment by kdave** [comment]
`btrfs device add` does discard by default and it can be disabled by `-K` or `--no-discard` (like for mkfs).

**Comment by kdave** [comment]
`replace start` does not do sicard, nor it has any other related options so that needs to be implemented.

**Comment by Forza-tng** [comment]
> `btrfs device add` does discard by default and it can be disabled by `-K` or `--no-discard` (like for mkfs).

This is good. It must be something in the virtual environment that makes btrfs believe the device doesn't support discards. As you can see the `blkdiscard` tool works, and `fstrim` works too on the mounted filesystem. I wonder why `fstrim` and `blkdiscard` works while `mkfs.btrfs` and `btrfs device add` doesn't?

**Comment by kdave** [comment]
The way the discard capability is detected may be different. What's done in btrfs-progs is to try discard on an empty range and if this does not fail whole device is trimmed. That the range is empty could be problematic in your environment.

The "standard" way to detect the capability is to check sysfs queue file `discard_granularity` if the value is > 0. In your case it is.

**Comment by kdave** [comment]
After the debugging session, it was really the problem, the driver does not like range of zero length. The fix is to do the recommeded detection from sysfs.

**Comment by kdave** [comment]
And the replace start + nodiscard is also in devel.
