### ISSUE TITLE
[Feature Request] Option to retain UUID when using btrfs-convert

### ISSUE THREAD

**Issue by damian101** [kdave/btrfs-progs#391]
Would be convenient.

**Comment by kdave** [comment]
https://lore.kernel.org/linux-btrfs/1357486331-4615-2-git-send-email-falbrechtskirchinger@gmail.com/ from 2013 implements that, there are some comments that haven't been addressed, but the feature is convenient indeed.

**Comment by kdave** [comment]
Now implemented and pushed to devel.
