### ISSUE TITLE
unprivileged `btrfs filesystem usage` reports bogus non-zero "Device missing" value

### ISSUE THREAD

**Issue by cmurf** [kdave/btrfs-progs#395]
kernel 5.14.0 (reproduces with 5.13.8 as well)
btrfs-progs 5.13.1

```
$ btrfs fi us /
WARNING: cannot read detailed chunk info, per-device usage will not be shown, run as root
Overall:
    Device size:		 411.35GiB
    Device allocated:		  53.01GiB
    Device unallocated:		 358.34GiB
    Device missing:		 411.35GiB
    Used:			  31.99GiB
    Free (estimated):		 379.16GiB	(min: 379.16GiB)
    Free (statfs, df):		 379.35GiB
    Data ratio:			      1.00
    Metadata ratio:		      1.00
    Global reserve:		 194.77MiB	(used: 0.00B)
    Multiple profiles:		        no

Data+Metadata,single: Size:53.01GiB, Used:31.99GiB (60.36%)

System,single: Size:4.00MiB, Used:12.00KiB (0.29%)
```

>    Device missing:		 411.35GiB

This is completely bogus. No devices are missing.

**Comment by kdave** [comment]
I wonder how much is it related to the warning, ie. not all information is available but something is printed nevertheless.

**Comment by kdave** [comment]
Yeah it's because of lack of the missing info, the value matches `Device size`.

**Comment by kdave** [comment]
So the problem was that the device size is read using an ioctl but that needs to open the device, that's not always possible for a regular user. I've added a fallback that reads it from sysfs. Patch in devel, thanks for the report.
