### ISSUE TITLE
Defrag -c is broken with progs-5.14

### ISSUE THREAD

**Issue by Forza-tng** [kdave/btrfs-progs#403]
With btrfs-progs it is no longer possible to use `-c<algo>` to defragment files. I've checked with others on #btrfs that have the same issue with different distros. 

```
# btrfs fi defrag -v -czstd qBit_swap.img
ERROR: unknown compression type: zstd

# btrfs fi defrag -v -clzo qBit_swap.img
ERROR: unknown compression type: lzo

# btrfs fi defrag -v -czlib qBit_swap.img
ERROR: unknown compression type: zlib
```

I'm using Gentoo Linux 5.13.12 and btrfs-progs 5.14.

**Comment by Artefact2** [comment]
Can reproduce on Arch Linux, linux 5.14.5.arch1-1 and btrfs-progs 5.14-1

**Comment by Zygo** [comment]
Commit f3a132fa1b8cd5852f9d844f13e86d2649ec2377 should check for "if (ret < 0)" not  "if (ret)" in `parse_compress_type_arg`

**Comment by lersek** [comment]
Clearly commit f3a132fa1b8cd was never tested (in isolation anyway), as every possible return value from the new `parse_compress_type()` function, namely `BTRFS_COMPRESS_ZLIB`, `BTRFS_COMPRESS_LZO`, `BTRFS_COMPRESS_ZSTD`, `-EINVAL`, was going to be nonzero, and as such, there would be no way for `parse_compress_type_arg()` to succeed.

**Comment by Conan-Kudo** [comment]
Can reproduce on Fedora Linux 34 as well, kernel 5.13.16-200.fc34 and btrfs-progs-5.14-2.fc34. This is also captured downstream as [RhBug:2005529](https://bugzilla.redhat.com/show_bug.cgi?id=2005529).

**Comment by kdave** [comment]
Thanks for the report, fixed in devel.

**Comment by kdave** [comment]
As this is breaking an important usecase I'll do a bugfix release soon (Monday or so).

**Comment by kdave** [comment]
Testcase added, closing.
