### ISSUE TITLE
ETA for scrub, improved status

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#41]
Scrub status could estimate run time, by calculating average progress on all devices. This can be tricky in case other system activity that will preempt the scrub io, but some kind of estimate could be given nevertheless.

The status report can be reworked so we can put more information there. Eg. do the key: value style of output, per device stats, continuous updates, bandwidth utilization, current progress, etc.

**Comment by gkowal** [comment]
I wrote an initial patch trying to address some of these features. In principal, getting the speed of scrub and estimated time to finish was relatively easy. Just to note, it works also per device. See pull #177.

**Comment by kdave** [comment]
The scrub status now contains ETA and bandwidth.

**Comment by kdave** [comment]
Implemented since 5.2.
