### ISSUE TITLE
qgroup limit: subvolid as argument not accepted

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#413]
Qu reports that subvolid as limit argument got broken in 5.14, caused by

```
commit cb5a542871f9307ab11aecbe72d1fd2a44836209 (refs/bisect/bad)
Author: David Sterba <dsterba@suse.com>
Date:   Mon Sep 6 20:10:02 2021 +0200

    btrfs-progs: factor out plain qgroupid parsing
```

**Comment by adam900710** [comment]
And the fix is:
https://patchwork.kernel.org/project/linux-btrfs/patch/20211011070937.32419-1-wqu@suse.com/

**Comment by kdave** [comment]
The failing fstest case has been updated to use full qgroupid and that should be the widely used format, so no exceptions in the commands.
