### ISSUE TITLE
'btrfs qgroup limit' failed (btrfs-progs pre-release 5.15-rc1)

### ISSUE THREAD

**Issue by wangyugui** [kdave/btrfs-progs#416]
xfstests(btrfs/099) is broken with progs pre-release 5.15-rc1

It seems NOT a feature change, just a bug.

```
# /usr/sbin/btrfs qgroup limit 134217728 5 /mnt/scratch
ERROR: invalid qgroupid or subvolume path: 5
failed: '/usr/sbin/btrfs qgroup limit 134217728 5 /mnt/scratch'
```

**Comment by adam900710** [comment]
It's a known one, and we have a patch for it:

https://patchwork.kernel.org/project/linux-btrfs/patch/20211011070937.32419-1-wqu@suse.com/

The problem is we're still not sure if we should make the single number qgroupid valid.

**Comment by wangyugui** [comment]
With this patch, xfstests(btrfs/099) passed.

Thanks a lot.  Let's close it once this patch is merged.

**Comment by wangyugui** [comment]
#413
