### ISSUE TITLE
'btrfs device stats' output 0 as corruption_errs, but 2 is expected(pre-release 5.15-rc1)

### ISSUE THREAD

**Issue by wangyugui** [kdave/btrfs-progs#417]
xfstests(btrfs/215) is broken with progs pre-release 5.15-rc1

It seems not a feature change, just a bug.

'btrfs device stats' output 0 as corruption_errs, but 2 is expected.

**Comment by wangyugui** [comment]
mkfs.btrfs (pre-release 5.15-rc1, 5.14.2)              &  'btrfs device stat'(pre-release 5.15-rc1, 5.14.2)  :  xfstests(btrfs/215)  FAIL
mkfs.btrfs -O no-holes -R free-space-tree(5.10)  &  'btrfs device stat'(pre-release 5.15-rc1, 5.14.2)  :  xfstests(btrfs/215)  PASS
mkfs.btrfs -O no-holes -R free-space-tree(5.10)  &  'btrfs device stat'( 5.10)                                      :  xfstests(btrfs/215)  PASS

'btrfs device stat'(pre-release 5.15-rc1, 5.14.2) correctly output the value that get from kernel.

Is this a feature change OR bug of 'mkfs.btrfs (pre-release 5.15-rc1, 5.14.2)'?

**Comment by wangyugui** [comment]
This is because mkfs.btrfs '-m DUP' default for single SSD too since this release.

Add '-m single' to xfstests(btrfs/215) test script to avoid this failure.

**Comment by adam900710** [comment]
No, it's not that simple.

If you go misc-next branch, that would cause a different problem.

In fact btrfs/215 will always fail due to nospace_cache mount option will prevent us to mount an fs with v2 cache.

I have sent a fix for the bug anyway.
Thanks for the report.

**Comment by kdave** [comment]
Right, the defaults in mkfs could change test results like you observe, it's expected but good to know in which cases in particular.
