### ISSUE TITLE
reflink takes 27s with the mkfs.btrfs (pre-release 5.15-rc1)

### ISSUE THREAD

**Issue by wangyugui** [kdave/btrfs-progs#418]
xfstests(generic/297) failed becase reflink takes 27s with the mkfs.btrfs (Btrfs progs pre-release 5.15-rc1)

reflink of 8589934592 bytes took 27 seconds
reflink didn't stop in time, n=8589934592 t=27

We test xfstests(generic/297)  with mkfs.btrfs (Btrfs progs 5.10.1) with some patch to enable no-holes / free-space-tree,
but this case works well.

So there is some bug in mkfs.btrfs to make btrfs kernel work badly, or some change in mkfs.btrfs to make some btrfs kernel bug happen more easy?

**Comment by wangyugui** [comment]
This problem happen when 'mkfs.btrfs -m DUP' with the frequency about 50%.
but yet not happen when 'mkfs.btrfs -m single'.

so this is a btrfs kernel problem about DUP metadata.

**Comment by wangyugui** [comment]
it is not a btrfs-progs issue, so close it.

**Comment by kdave** [comment]
There is a label for kernel-related issues but it's not meant to be a substitute for genuine kernel bug reports.
