### ISSUE TITLE
Segfault in find_good_parent when IS_ERR(parent)

### ISSUE THREAD

**Issue by dcepelik** [kdave/btrfs-progs#423]
Hello,

I've hit a bug today in btrfs-progs which I believe is present in current master:

https://github.com/kdave/btrfs-progs/blob/4d06e4a13d1ce1849a60b68969bc385ab736ddf7/cmds/send.c#L176-L177

When you jump into this error handling code from:

https://github.com/kdave/btrfs-progs/blob/4d06e4a13d1ce1849a60b68969bc385ab736ddf7/cmds/send.c#L106-L112

You can still have IS_ERR(parent), and de-referencing that blows up.

I think the correct way is to further discriminate in the if-clause between parent being NULL and parent being an error code.

Please let me know if I can provide more info :).

**Comment by dcepelik** [comment]
There's an isomorphic issue in:

https://github.com/kdave/btrfs-progs/blob/4d06e4a13d1ce1849a60b68969bc385ab736ddf7/cmds/receive.c#L357-L360

**Comment by kdave** [comment]
Thanks for the report, now fixed in devel.

**Comment by dcepelik** [comment]
Thanks for the fix :).
