### ISSUE TITLE
btrfs subvolume create --parents, as in mkdir

### ISSUE THREAD

**Issue by ghost** [kdave/btrfs-progs#429]
Hi, 
It would be nice to have a `-p` option in `btrfs subvolume create`, so that relevant parent directories are automatically created if needed, replicating the `mkdir` behavior from coreutils :

see https://www.gnu.org/software/coreutils/manual/html_node/mkdir-invocation.html
```
‘-p’
‘--parents’

    Make any missing parent directories for each argument, setting ....
```

Have a good day !

**Comment by kdave** [comment]
Why not, it could make things easier. The `mkdir` syscall expects the path components to exist, so the path must be split which could be potentially tricky, though eg. `realpath` can be used to resolve and normalize the path and we'd just chop the last component which would be the subvolume name.

**Comment by Forza-tng** [comment]
I think it would be useful if we could create multiple subvolumes in one command as well. Perhaps this should be a separate issue though? 

```
# btrfs sub create foo bar
btrfs subvolume create: exactly 1 argument expected, 2 given
```

**Comment by clavelc** [comment]
```
mkdir -P /home/<user>/.local/share/libvirt/
btrfs sub create /home/<user>/.cache
btrfs sub create /home/.local/share/Trash
btrfs sub create /home/.local/share/libvirt/images
```
could just become 
```
btrfs sub create -P /home/<user>/{.cache,.local/share/{libvirt/images,Trash}}
```
exactly like mkdir does :)

**Comment by realwakka** [comment]
I've submitted a patch for this issue. please check it and review will be welcome :)
https://patchwork.kernel.org/project/linux-btrfs/patch/20220220031254.58297-1-realwakka@gmail.com/

**Comment by kdave** [comment]
Added to devel, with a test case, thanks.
