### ISSUE TITLE
Error occurred when doing compile  on CentOS

### ISSUE THREAD

**Issue by wangmingyu84** [kdave/btrfs-progs#439]
btrfs-tools compile failed on centos:

| kernel-shared/volumes.o: In function `create_chunk':
| volumes.c:(.text+0x1443): undefined reference to `__ALIGN_KERNEL'
| collect2: error: ld returned 1 exit status
| make: *** [Makefile:587: btrfs-corrupt-block] Error 1
| ERROR: oe_runmake failed

I noticed that kerncompat.h removed #include <linux/kernel.h.
But on CentOS, __ALIGN_KERNEL is defined in linux/kernel.h. 
After deleting this file, it will not compile correctly

**Comment by kdave** [comment]
Referencing issure #433, similar problem and the same fix. It's in devel, I've verified taht centos 7 and 8 build properly. I'll do a bugfix release soon. This is the commit that fixes it b0cfe12c4d4b8b4ef335cdf4ddefcbdcd1b70d58.
