### ISSUE TITLE
GPG key is invalid for btrfs-progs 4.11

### ISSUE THREAD

**Issue by sandalle** [kdave/btrfs-progs#44]
Files downloaded from https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/ .

`$ gpg --verify /var/spool/sorcery/btrfs-progs-v4.11.tar.sign /var/spool/sorcery/btrfs-progs-v4.11.tar.xz
gpg: Signature made Thu May 18 07:16:47 2017 PDT using RSA key ID D76D583B
gpg: requesting key D76D583B from hkp server pgp.mit.edu
gpg: key D76D583B: public key "David Sterba <dsterba@suse.cz>" imported
gpg: public key EB203A7A is 4060667 seconds newer than the signature
gpg: 3 marginal(s) needed, 1 complete(s) needed, classic trust model
gpg: depth: 0  valid:   4  signed:  21  trust: 0-, 0q, 0n, 0m, 0f, 4u
gpg: depth: 1  valid:  21  signed:  84  trust: 0-, 1q, 0n, 15m, 5f, 0u
gpg: depth: 2  valid:  77  signed:  24  trust: 0-, 0q, 7n, 52m, 18f, 0u
gpg: depth: 3  valid:   4  signed:   2  trust: 0-, 0q, 0n, 2m, 2f, 0u
gpg: depth: 4  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 1f, 0u
gpg: next trustdb check due at 2035-01-22
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg: BAD signature from "David Sterba <dsterba@suse.cz>"
`

Yet the SHA256 hash matches https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/sha256sums.asc .
` sha256sum /var/spool/sorcery/btrfs-progs-v4.11.tar.*
addf707e41870c284ba17356745bef6c5b4ff2232ebf62b216954ec21e79b5d3  /var/spool/sorcery/btrfs-progs-v4.11.tar.sign
e17a68cc52a27d905b715445e91ddbaa4d42de4847d54836d6ed21e012dabf0e  /var/spool/sorcery/btrfs-progs-v4.11.tar.xz`

**Comment by sandalle** [comment]
Nevermind, I need to learn to read, sorry about the noise. :)

The GPG signature is for the uncompressed tar.
`
$ gpg --verify /var/spool/sorcery/btrfs-progs-v4.11.tar.sign /var/spool/sorcery/btrfs-progs-v4.11.tar
gpg: Signature made Thu May 18 07:16:47 2017 PDT using RSA key ID D76D583B
gpg: Good signature from "David Sterba <dsterba@suse.cz>"
gpg:                 aka "David Sterba <dave@jikos.cz>"
gpg:                 aka "David Sterba <dsterba@suse.com>"
gpg:                 aka "David Sterba <kdave@kernel.org>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: F2B4 1200 C54E FB30 380C  1756 C565 D5F9 D76D 583B
`

**Comment by kdave** [comment]
Yeah, the signature is on the tar so there can be bogh gz and xz and just one signature.
