### ISSUE TITLE
5.16.1 build failure with configure --disable-zoned

### ISSUE THREAD

**Issue by chris2553** [kdave/btrfs-progs#445]
Hi. btrfs-progs-5.16.1 fails to build on my system.  5.16.builds without problem, so this is a regression. This is because, on my system, BTRFS_ZONED will not be defined,  which, in turn will leave zoned_profile_supported undefined in kernel-shared/zoned.h.

The error message is:
/usr/bin/ld: mkfs/main.o: in function `main':
/home/chris/rpm/BUILD/btrfs-progs-v5.16.1/mkfs/main.c:1352: undefined reference to `zoned_profile_supported'
/usr/bin/ld: /home/chris/rpm/BUILD/btrfs-progs-v5.16.1/mkfs/main.c:1353: undefined reference to `zoned_profile_supported'
collect2: error: ld returned 1 exit status
make: *** [Makefile:630: mkfs.btrfs] Error 1

With the patch below applied, the build completes, although I will need your advice as to whether it results in a  mkfs.btrfs that will function correctly.
<
--- btrfs-progs-v5.16.1/kernel-shared/zoned.h.orig      2022-02-06 11:09:39.728318915 +0000
+++ btrfs-progs-v5.16.1/kernel-shared/zoned.h   2022-02-06 11:11:21.772323202 +0000
@@ -145,6 +145,11 @@ static inline int btrfs_reset_dev_zone(i
        return 0;
 }
 
+static inline bool zoned_profile_supported(u64 flags)
+{
+    return false;
+}
+
 static inline bool zone_is_sequential(struct btrfs_zoned_device_info *zinfo,
                                      u64 bytenr)
 {
>

**Comment by chris2553** [comment]
I see the patch isn't displaying properly in my initial post and I've not been able to figure out how to fix that. Consequently, I've attached the patch in a zip archive.
[btrfs-progs-v5.16.1-add-missing-definition.patch.zip](https://github.com/kdave/btrfs-progs/files/8014947/btrfs-progs-v5.16.1-add-missing-definition.patch.zip)

**Comment by kdave** [comment]
You can format a diff as a quote in triple backticks (```diff). So yeah it's a regression, the non-zoned build is missing definition of the function, I can apply the fix from the zip file, thanks.

**Comment by kdave** [comment]
Fixed in devel, thanks.
