### ISSUE TITLE
btrfs filesystem df versus btrfs filesystem

### ISSUE THREAD

**Issue by sluedecke** [kdave/btrfs-progs#448]
I have recently converted a 1.8 TB ext4 filesystem with roughly 120 GB of free space to btrfs.  Following the documentation of `btrfs convert` I started a defragmentation which quickly filled up the remaining free space before aborting due to 'no free space'.  I then added a second device to the filesystem, hoping to have enough room to smoothe things out.  But it did not work like that.  I deleted quite some GB worth of data (cache files etc) and invoked the defragmentation again.  The second defragmentation attempt filled this extra device just as fast as the first one. 

So now I have a filesystem where 

`sudo btrfs fi du -s /home/FOLDER/` reports:

```
     Total   Exclusive  Set shared  Filename
   1.58TiB   664.97GiB   948.56GiB  /home/FOLDER/

```

Looks good and I would like to remove the extra device now, but `sudo btrfs fi usage -T /home/FOLDER` tells me:

```
Overall:
    Device size:		   1.88TiB
    Device allocated:		   1.87TiB
    Device unallocated:		   2.94GiB
    Device missing:		     0.00B
    Used:			   1.87TiB
    Free (estimated):		   3.30GiB	(min: 3.30GiB)
    Free (statfs, df):		   3.30GiB
    Data ratio:			      1.00
    Metadata ratio:		      1.00
    Global reserve:		 512.00MiB	(used: 96.00KiB)
    Multiple profiles:		        no

                              Data      Metadata System               
Id Path                       single    single   single    Unallocated
-- -------------------------- --------- -------- --------- -----------
 1 /dev/mapper/_dev_nvme1n1p5   1.75TiB  5.92GiB         -     2.74GiB
 3 /dev/sda1                  116.00GiB  3.01GiB  32.00MiB   207.32MiB
-- -------------------------- --------- -------- --------- -----------
   Total                        1.87TiB  8.93GiB  32.00MiB     2.94GiB
   Used                         1.86TiB  6.81GiB 304.00KiB    

```

I am probably missing something important here, can you please give me a hint?

. How much space is actually in use now?
. If it is the amount from `du`, how do I best get the free space back to be unallocated?
. What is the best approach to get the second device removed again (this currently fails due to 'no space left')?

**Comment by sluedecke** [comment]
Most probably I am not ready for btrfs yet.  So for the sake of being able to use the filesystem I went back to ext4.

**Comment by kdave** [comment]
If defrag started to consume space that's most likely because you still had the original image in `ext2_saved/image`, and the remaining space was not sufficient to hold the newly defragmented data. As defrag works, it breaks the shared links, ie. undoes the COW of the blocks and requires space for that. This is documented in the manual page, the order of the steps matter, you skipped one and encountered problems.
