### ISSUE TITLE
docs: btrfs-man5: nonsensical sentence

### ISSUE THREAD

**Issue by Kasijjuf** [kdave/btrfs-progs#45]
In the file [Documentation/btrfs-man5.asciidoc](https://github.com/kdave/btrfs-progs/blob/master/Documentation/btrfs-man5.asciidoc#file-attributes), in the File Attributes section, the description for the 'd' attribute is nonsensical.

"on BTRFS the attribute can be set/unset on no other special handling is done"

This description first appeared in Documentation/btrfs-mount.asciidoc in commit a8829f5335a121928cf773ba00be4530bf0267c0 before that file was renamed to Documentation/btrfs-man5.asciidoc in commit 32c063ccb73dc11e880a575f30e921ca64b8c520.

**Comment by kdave** [comment]
It should be "on BTRFS the attribute can be set/unset *but* no other special handling is done

**Comment by kdave** [comment]
Fixed in devel.
