### ISSUE TITLE
possible regression in opts parser

### ISSUE THREAD

**Issue by ntxy** [kdave/btrfs-progs#47]
-p seems positional now.

`btrfs send /foo -p /bar` 

throws "ERROR: unable to resolve -p"

version tested: 4.11
4.9.1 didn't have this problem

**Comment by kdave** [comment]
The parser has been updated so the mixed order of non-option arguments and arguments is not valid anymore. It should have never been. The common syntax is 'command [options] [arguments]'. Please fix your scripts.

The parser update prepares for an extended syntax where we could have global options right after 'btrfs':
btrfs [--global --options ...] subcommand [--subcommand --options] arguments...

**Comment by adam900710** [comment]
@kdave Well I totally understand that supporting global options is a good idea, but I think it's still quite annoying for end users to force the arrangment of argumanges and options.

What about introducing `subcommand` as an anchor to tell getopt parser to stop parsing?
That's to say, we glocal options will only be valid between argv[0] and `subcommand`.
While we still allow re-order arguments and subcommand options if there is no next level anchor.

Thanks,
Qu
