### ISSUE TITLE
btrfs-progs no longer supports settings compression when CoW is disabled

### ISSUE THREAD

**Issue by dalto8** [kdave/btrfs-progs#473]
As of 5.17 it is no longer possible to set compression once CoW is disabled.

For example:
```text
chattr +C testfile
btrfs property set testfile compression none
```
This results in `ERROR: failed to set compression for testfile: Invalid argument`

I am not sure if this is a deliberate change, an issue with btrfs progs or an issue with btrfs itself.

If this should be reported somewhere else, please let me know.

**Comment by kdave** [comment]
This is intentional, please see the explanation in https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0e852ab8974cd2b5946766b2d9baf82c78ace03d .
