### ISSUE TITLE
Enhancement: Add csum type to dmesg output 

### ISSUE THREAD

**Issue by Forza-tng** [kdave/btrfs-progs#483]
It would be useful to see the current csum type in dmesg when mounting filesystems.

Currently I see  the following when mounting a single device filesystem using kernel-5.17.12
```
[172836.689873] BTRFS info (device sdc2): flagging fs with big metadata feature
[172836.689880] BTRFS info (device sdc2): use zstd compression, level 5
[172836.689883] BTRFS info (device sdc2): using free space tree
[172836.689884] BTRFS info (device sdc2): has skinny extents
```
It could be extended as

```
[172836.689873] BTRFS info (device sdc2): flagging fs with big metadata feature
[172836.689879] BTRFS info (device sdc2): using xxhash64 checksum algorithm
[172836.689880] BTRFS info (device sdc2): using zstd compression, level 5
[172836.689883] BTRFS info (device sdc2): using free space tree
[172836.689884] BTRFS info (device sdc2): has skinny extents
```

**Comment by kdave** [comment]
It increases the number of messages per mount, which I think is already high and some messages are just noise (like "flagging fs with big metadata feature"), but the checksum is configurable and can be useful for overview. Additionally the actual implementation can be printed (similar to what the module load printes, eg. `Btrfs loaded, crc32c=crc32c-intel, assert=on, zoned=yes, fsverity=yes`).

**Comment by Forza-tng** [comment]
I don't mind having a few status messages in dmesg. But you're right that the big metadata feature message is more or less not very useful. The checksum algorithm is something that you are working on being changable, so that status message becomes more useful then. 

I do wonder if the module loading message could print the other checksums in additin to crc32c that it supports, and what HW/CPU implementation is used for them?

It is of course already possible to check all of this with `btrfs inspect-internal`, though most users don't know how to use that command.

**Comment by kdave** [comment]
Example:

`[   25.323662] BTRFS info (device vdb): using sha256 (sha256-generic) checksum algorithm`

the output is the same as the sysfs `FSID/checksum` file.

Printing the implementation at module load time makes sense perhaps only for crc32c as it is used for internal hashing, not just for data/metadata checksums, so we have the crypto object to ask about the implementation. If we wanted to print that for all algorithms that would mean to create instances of all the crypto objects. The crypto modules are soft dependencies and may not exist or may force loading the generic implementation (eg. when triggered from initrd). I think it would be confusing and not reliable as the file `/proc/crypto` says what is actually available.

**Comment by kdave** [comment]
Patch in 5.20 queue, closing.

**Comment by kdave** [comment]
> Patch in 5.20 queue, closing.

Thumbs down? Why, have I missed something?

**Comment by Forza-tng** [comment]
> > Patch in 5.20 queue, closing.
> 
> Thumbs down? Why, have I missed something?

Oups. Thick fingers! Thank you very much for the fast fix! 🙏

**Comment by kdave** [comment]
Ok :)
