### ISSUE TITLE
Enhancement: move 'btrfs replace' to 'btrfs device replace' 

### ISSUE THREAD

**Issue by Forza-tng** [kdave/btrfs-progs#484]
I've seen quite a few people on the #btrfs IRC channel who  used `btrfs device add` + `btrfs device delete`, when they really should have used `btrfs replace` instead. I believe it is easy for regular users to overlook the replace option because it isn't available in `btrfs device --help`. I've done this mistake myself... 

The [man page](https://btrfs.readthedocs.io/en/latest/btrfs-device.html)  says: ***The btrfs device command group is used to manage devices of the btrfs filesystems.***

From a user experience point of view, I think that `replace` seems to logically fit together with `device add` and `device remove` and not in a separate subcommand.

I propose to move `btrfs replace` into the `btrfs device` group and leave an alias for backwards compatibility for the time being. I believe that this will make it easier for users to understand when to use replace and when to use add and remove.

**Comment by kdave** [comment]
The `btrfs device replace <subcommand>` can be long to type but adding an alias is ok.

**Comment by kdave** [comment]
Pushed to devel. The help text now mentions only the 'btrfs replace' way, as it's used in 2 places and cannot be parametrized. The separate manual page of replace makes a bit more sense as it's a lot of text, but manual page parts can be included so this can be revisited too.

**Comment by Forza-tng** [comment]
Looks good to me. 

Perhaps we can simply add the same text `Alias of whole command group *btrfs replace* for convenience. See 'btrfs-replace(8)'.`  to the `btrfs-device` man page too?

File: `https://github.com/kdave/btrfs-progs/blob/master/Documentation/btrfs-device.rst`
```
delete <device>|<devid> [<device>|<devid>...] <path>
        Alias of remove kept for backward compatibility

+ replace <subcommand> <args>
+        Alias of whole command group *btrfs replace* for convenience. See ``btrfs-replace(8)``.
+
ready <device>
```

Thank you.
