### ISSUE TITLE
Question: Copy a healthy metadata to second same one for single partition or single disk or RAID 0

### ISSUE THREAD

**Issue by Zesko** [kdave/btrfs-progs#489]
I have read a bit and learned someone has some problem with BTRFS, unable to mount partition and unable to recover data .

For example:
* https://forum.garudalinux.org/t/btrfs-failure/19135 like
* https://wiki.tnonline.net/w/Btrfs/Parent_Transid_Verify_Failed

If one metadata alone is corrupted, that is very bad, I think.

My question is, is that possible to make two same metadata (Single disk or single partition or RAID 0 has two same metadata) if one of 2 is broken but last one survives to recover possible data? (Idea: Broken metadata is easily repaired or overwritten which is the same as healthy metadata.)

I think two same metadata like twins give you a good chance to recover data when using single partition or disk, and make mount more stable without failure of mount with partition.

Are there new problems when using two identical metadata? Performance issue? implementation problem?

**Comment by Zesko** [comment]
How to determine if metadata is healthy or not?

I think,maybe it needs a new feature: A inspection tool will check metadata and all nodes in B-Tree and compare it with second metadata, if they correctly match together.

**Comment by Zesko** [comment]
@Forza-tng 

That is good, thanks!
Is there the document about that?

How can I find if I have two copies of each metadata block ? I am using Linux Kernel 5.18.

**Comment by Forza-tng** [comment]
> @Forza-tng
> 
> That is good, thanks! Is there the document about that?
> 
> How can I find if I have two copies of each metadata block ? I am using Linux Kernel 5.18.

You can use `btrfs filesystem usage /mnt/btrfs`. It will show DUP metadata profile:
```
Overall:
    Device size:                 227.89GiB
    Device allocated:            116.02GiB
    Device unallocated:          111.86GiB
    Device missing:                  0.00B
    Used:                         60.85GiB
    Free (estimated):            162.32GiB      (min: 106.39GiB)
    Free (statfs, df):           162.32GiB
    Data ratio:                       1.00
    Metadata ratio:                   2.00
    Global reserve:              512.00MiB      (used: 0.00B)
    Multiple profiles:                  no
Data,single: Size:106.01GiB, Used:55.55GiB (52.40%)
   /dev/nvme0n1p5        106.01GiB
Metadata,DUP: Size:5.00GiB, Used:2.65GiB (53.04%)
   /dev/nvme0n1p5         10.00GiB
System,DUP: Size:8.00MiB, Used:16.00KiB (0.20%)
   /dev/nvme0n1p5         16.00MiB
Unallocated:
   /dev/nvme0n1p5        111.86GiB 
```

https://btrfs.readthedocs.io/en/latest/mkfs.btrfs.html?highlight=Profile#profile-layout
https://wiki.tnonline.net/w/Btrfs/Profiles

**Comment by Zesko** [comment]
Oh, I use all singles
```
Data,single: Size:940.00GiB, Used:875.88GiB (93.18%)
   /dev/nvme0n1p2        940.00GiB
Metadata,single: Size:5.00GiB, Used:3.77GiB (75.33%)
   /dev/nvme0n1p2          5.00GiB
System,single: Size:32.00MiB, Used:144.00KiB (0.44%)
   /dev/nvme0n1p2         32.00MiB
Unallocated:
   /dev/nvme0n1p2        891.96GiB

```

**Comment by Zesko** [comment]
I installed Manjaro in VM, oh DUP profiles are default.

![Screenshot_20220701_114248](https://user-images.githubusercontent.com/17826352/176870118-d229fadc-9fc9-4eb7-b2ab-1176fd878e89.png)


When are DUP profiles default for single disk?

**Comment by Zesko** [comment]
Sorry, this is already in the document:
>  This has changed in version 5.15 to be always dup.

**Comment by Forza-tng** [comment]
> Oh, I use all singles
> 
> ```
> Data,single: Size:940.00GiB, Used:875.88GiB (93.18%)
>    /dev/nvme0n1p2        940.00GiB
> Metadata,single: Size:5.00GiB, Used:3.77GiB (75.33%)
>    /dev/nvme0n1p2          5.00GiB
> System,single: Size:32.00MiB, Used:144.00KiB (0.44%)
>    /dev/nvme0n1p2         32.00MiB
> Unallocated:
>    /dev/nvme0n1p2        891.96GiB
> ```
> 
> But the profiles "Single" are default by Manjaro installation when using a single partition in a disk

You can use `btrfs balance` to convert your metadata to DUP.

**Comment by Zesko** [comment]
> You can use btrfs balance to convert your metadata to DUP.

I tried it in my VM (Testing) that is the same as my system.

![Screenshot_20220701_120514](https://user-images.githubusercontent.com/17826352/176876334-27ecfd33-191a-4a4d-9019-1ad4d5541af4.png)

**Comment by Forza-tng** [comment]
> > You can use btrfs balance to convert your metadata to DUP.
> 
> I tried it in my VM (Testing) that is the same as my system.
> 
> ![Screenshot_20220701_120514](https://user-images.githubusercontent.com/17826352/176876334-27ecfd33-191a-4a4d-9019-1ad4d5541af4.png)

https://btrfs.readthedocs.io/en/latest/btrfs-balance.html

`btrfs balance start -mconvert=DUP /`

**Comment by Zesko** [comment]
Thanks!
It works

```
Data,single: Size:940.00GiB, Used:875.99GiB (93.19%)
   /dev/nvme0n1p2        940.00GiB
Metadata,DUP: Size:5.00GiB, Used:3.78GiB (75.56%)
   /dev/nvme0n1p2         10.00GiB
System,DUP: Size:32.00MiB, Used:144.00KiB (0.44%)
   /dev/nvme0n1p2         64.00MiB
Unallocated:
   /dev/nvme0n1p2        886.92GiB
```

Are they all ok?

**Comment by Forza-tng** [comment]
Yes, looks good.

As for maintenance you might want to read up on doing regular scrubs etc. You can also get good help in the #brtfs irc/matrix chat rooms.
