### ISSUE TITLE
Initialism "VFS" never defined

### ISSUE THREAD

**Issue by Kasijjuf** [kdave/btrfs-progs#49]
In the file [btrfs-device.asciidoc](https://github.com/kdave/btrfs-progs/blob/devel/Documentation/btrfs-device.asciidoc) in the section about the "remove" subcommand there appears this message:

> It is not possible to delete the device that was used to mount the filesystem. This is a limitation given by the VFS.

The initialism, "VFS", is not used anywhere else in the document nor is its meaning defined. This section of the document was written by @kdave.

**Comment by kdave** [comment]
VFS = the virtual filesystem layer, the generic layer to any filesystem. Anyway, the note is wrong, the mounted device can be deleted, so I'll remove it. Thanks.
