### ISSUE TITLE
`btrfs send` errors when used on a ro-mounted fs but the subvol isn't ro

### ISSUE THREAD

**Issue by 25pwn** [kdave/btrfs-progs#493]
`btrfs send` gives `ERROR: subvolume ${subvol} is not read-only` when the fs is mounted as ro but `${subvol}` is a non-ro subvol.

**Comment by Forza-tng** [comment]
> `btrfs send` gives `ERROR: subvolume ${subvol} is not read-only` when the fs is mounted as ro but `${subvol}` is a non-ro subvol.

I means that the subvol itself has to be ro, not that the filesystem should be ro.

You can make a ro snapshot that can be used with send with `btrfs subvolume snapshot -r`.

**Comment by kdave** [comment]
Send requires that the subvolume is immutable during the operation, it's not even possible to flip the ro flag when it's running. The read-only mount does not guarantee that, there can be another writable mount of the same subvolume, this would break send.

**Comment by 25pwn** [comment]
Sorry, I never got the notifications for these
> 
> @25pwn It means that the subvol itself has to be ro, not that the filesystem should be ro.
> 
> You can make a ro snapshot that can be used with send with `btrfs subvolume snapshot -r`.

@Forza-tng What I (wrongly) believed was that ro-mounted subvols are immutable, therefore they should be `send`able.

> Send requires that the subvolume is immutable during the operation, it's not even possible to flip the ro flag when it's running. The read-only mount does not guarantee that, there can be another writable mount of the same subvolume, this would break send.

@kdave I see. Though this would be a niche feature, could you see this(`send` when subvol is rw but immutable due to only being mounted ro etc.) being implemented? If I were to make these changes myself, would you accept the pull request?

**Comment by kdave** [comment]
> Though this would be a niche feature, could you see this(`send` when subvol is rw but immutable due to only being mounted ro etc.) being implemented? If I were to make these changes myself, would you accept the pull request?

The problem is that it's not possible to implement. There's no way to prevent changing any file from the rw subvolume during the send from another mount. In a very limited case "I know what am I doning" yes, but any accidental change would lead to corruption of the send stream and this would lack safety for general case.

**Comment by 25pwn** [comment]
Understood, thank you for answering

**Comment by kdave** [comment]
I've added a note about that to send manual page.
