### ISSUE TITLE
<dev> ?== <devid> ?== <device>

### ISSUE THREAD

**Issue by Kasijjuf** [kdave/btrfs-progs#50]
In reading the file [btrfs-device.asciidoc](https://github.com/kdave/btrfs-progs/blob/devel/Documentation/btrfs-device.asciidoc) I noticed the parameter notation for the subcommands varies from command to command. For example:

_add_ accepts one or more **\<dev>**
_remove_ accepts one or more **\<dev>** or **\<devid>**
_ready_ accepts a single **\<device>**

What is the difference between **\<dev>**, **\<devid>**, and **\<device>**?

**Comment by kdave** [comment]
dev is supposed to be a path to device  (/dev/sda1 etc), devid is the numeric identifier of a device within the filesystem

**Comment by kdave** [comment]
We could unify the naming in all pages and document that in the "Command syntax" section to the main page. So I suggest to drop the short '<dev>' and replace with '<device>'.  Please let me know if you're going to send a patch/pull for that (otherwise I'll do that myself).

**Comment by Kasijjuf** [comment]
> dev is supposed to be a path to device (/dev/sda1 etc), devid is the numeric identifier of a device within the filesystem

What about **\<device>** then? Any different than **\<dev>**?


> So I suggest to drop the short '' and replace with ''.

What? I think the markdown parser ate your sentence. Did you mean to say:

"
So I suggest to drop the short ''\<dev>" and replace with ''\<device>".
"

**Comment by kdave** [comment]
Hehe, you're right about both. The idea is to replace shortened dev with device.
