### ISSUE TITLE
Problem compiling with glibc >=2.36

### ISSUE THREAD

**Issue by lucabonnix** [kdave/btrfs-progs#501]
With incompatibility introduced in glibc 2.36 between sys/mount.h and linux/mount.h (https://sourceware.org/glibc/wiki/Release/2.36#Usage_of_.3Clinux.2Fmount.h.3E_and_.3Csys.2Fmount.h.3E ), "common/device-utils.c" no more compiles.

Proposed patch on gentoo https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-fs/btrfs-progs/files/btrfs-progs-5.18.1-glibc-2.36.patch?id=bd4e049b8809027727fc0f34f6ae30206d40781b (removing "#include <sys/mount.h>") seems to work also with ancient glibc (tested 2.23).

**Comment by kdave** [comment]
Will be fixed in 5.19, fix is in devel "btrfs-progs: use linux mount.h instead of sys/mount.h"

**Comment by lucabonnix** [comment]
Thanks!
