### ISSUE TITLE
escape newlines in btrfs receive --dump dest paths

### ISSUE THREAD

**Issue by ov2k** [kdave/btrfs-progs#510]
btrfs receive --dump generally handles paths with newlines.  However, when the path is an op-specific parameter, special characters are not escaped.  The example below illustrates the issue with the `dest` parameter of the `rename` operation, but I think this affects other operations that pass string parameters.

btrfs-progs v5.16.2, linux 5.15.0-47-generic (Ubuntu 22.04)

```
$ btrfs subvol create foo
$ touch 'foo/a
> b'
$ btrfs property set foo ro true
$ sudo btrfs send --no-data foo | btrfs receive --dump
...
mkfile          ./foo/o257-144794-0
rename          ./foo/o257-144794-0             dest=./foo/a
b
...
utimes          ./foo/a\nb                      atime=2022-09-09T11:40:12-0400 mtime=2022-09-09T11:40:12-0400 ctime=2022-09-09T11:40:12-0400
```

**Comment by kdave** [comment]
Thanks, that looks like a bug, the strings should be encoded.

**Comment by kdave** [comment]
Fixed in devel.
