### ISSUE TITLE
block-group-tree compat=6.0

### ISSUE THREAD

**Issue by CorrosiveTruths** [kdave/btrfs-progs#523]
Hi! Running mkfs.btrfs -R list-all has this line:

block-group-tree    - block group tree to reduce mount time (compat=6.0)

It doesn't work with 6.0, however - you get:

BTRFS error: cannot mount read-write because of unsupported optional features (0x8)
BTRFS error: open_ctree failed

It should be either compat=6.1 or in some way marked experimental, like mentioned in the changelog?

Both mkfs.btrfs and btrfstune will just let you create / convert filesystems that won't work rw on the running kernel, maybe btrfstune should have a warning too?

Lastly, the feature isn't in the mkfs.btrfs.rst file, although this may well be by design as it is experimental according to the changelog.

**Comment by kdave** [comment]
The experimental features could have bugs or missing documentation, it'll be added incrementally as problems appear. So yeah the version is wrong, right version is 6.1, will be fixed. The warnings are a good idea in general for all experimental features.

**Comment by kdave** [comment]
All commands that want to use experimental feature will print a warning.
