### ISSUE TITLE
proto 2 kernel version

### ISSUE THREAD

**Issue by CorrosiveTruths** [kdave/btrfs-progs#529]
Hi, man btrfs-send suggests that, starting with kernel 5.18, proto 2 and compressed-data should be available in btrfs send. But it only works with 6.0.

On 5.19 for example you get this:
uname -r
5.19.15-gentoo-dist
btrfs send --proto=2 snapshot > /dev/null
ERROR: requested version 2 but kernel supports only 1

**Comment by kdave** [comment]
Thanks for the report, it's a typo, it should really be 6.0.

**Comment by kdave** [comment]
Fixed in devel.
