### ISSUE TITLE
add documentation/functionality to find out the resume_offset of a swapfile

### ISSUE THREAD

**Issue by calestyo** [kdave/btrfs-progs#533]
Hey.

According to [recommendations on the internet](https://wiki.archlinux.org/title/Power_management/Suspend_and_hibernate#Hibernation_into_swap_file_on_Btrfs), one cannot determine the offset of a swapfile on btrfs the "usual way" (i.e. using `filefrag`) because that wouldn't show the real physical offset on the device.

Could you please add some proper documentation and/or functionality for people to easily determine the correct offset value on btrfs?

Even better would of course be, if the kernel allowed to simply give the pathname of the file instead of `resume_offset`, but not sure if that can be easily done.

And perhaps also add any other btrfs specifics (should there be any), when using a swap file for hibernation?

Thanks,
Chris.

**Comment by calestyo** [comment]
Hey David.

If this is just `docs`, does that mean that Omar’s special `btrfs_map_physical` ([[0]](https://github.com/osandov/osandov-linux/blob/master/scripts/btrfs_map_physical.c)) tool is obsolete (for the purpose of hibernation swap files)?

Thanks.

**Comment by kdave** [comment]
Documentation updated, the command status is tracked in #544.

**Comment by calestyo** [comment]
Hey @kdave.

Just some feedback on this:

Seems to work quite fine for me :-)

The only things that could perhaps be done:
- support `--label` (Not that I personally need it, but why support `--uuid` and not the other? Or also drop `--uuid` and simply always let people use `mkswap` instead if they want to set details.)
- Instead of `The command is a simplified version of 'mkswap', if you want to set label, page size, or other parameters please use 'mkswap' proper.` I'd perhaps write something like: `… use 'mkswap' on the swapfile generated with btrfs filesystem mkswapfile`. Especially since you've kept the pre-6.1 description on how to do it in `btrfs(5)`, novice users migh think that it's either `mkswapfile` with just these options... or doing everything manually with `mkswap`.
- Instead of `and the Swapfile feature description.` perhaps rater ``and the 'Swapfile Support' section of btrfs(5).` so that people easier find what you meant?

But all these are really just minor cosmetics. :-)

I could provide patches if you wish.

Cheers,
Chris.

**Comment by calestyo** [comment]
(with "work quite fine for me" I meant: for hibernation to a swapfile on top of dm-crypt/LUKS)
