### ISSUE TITLE
Can't cancel btrfs filesystem resize 6.0.1

### ISSUE THREAD

**Issue by CorrosiveTruths** [kdave/btrfs-progs#539]
Hi,

I have an array, /home, with four devices, devids 5-8.

With 6.0 I can cancel a running resize operation by calling btrfs fi re cancel /home.

With 6.0.1 with the same command I can't cancel the resize.

In both cases it returned: ERROR: cannot find devid: 1

**Comment by CorrosiveTruths** [comment]
I also tried btrfs fi re 8:cancel under 6.0.1, which also didn't work, returning:

ERROR: unable to start resize, another exclusive operation 'resize' in progress

**Comment by kdave** [comment]
That's probably caused by 55438f3930b23fdebeeda7b93ec00414c64a1361.

**Comment by kdave** [comment]
The first problem about devid is known, without arguments is assumes device 1, there's another issue for that. But that resize can't be cancelled is a new one.

**Comment by kdave** [comment]
I can't reproduce it, also the `8:cancel` syntax does not work, this returns EINVAL as the cancelation is for any resize in progress.

**Comment by CorrosiveTruths** [comment]
Hi, wrote a quick 'n' dirty reproducer script:

https://gist.github.com/CorrosiveTruths/f80bb4ed30ac220ac0a655e370135375

I probably need to formulate my confusion with the cancel syntax in another issue.

**Comment by kdave** [comment]
Thanks for the script, now I can reproduce it.

**Comment by kdave** [comment]
And it is indeed caused by commit 55438f3930b23fde, that's been reverted in devel (cancel works) and adding it back leads to enospc. The patch is quite simple and I don't see why it breaks it.
