### ISSUE TITLE
Defrag command default verbosity changed

### ISSUE THREAD

**Issue by CorrosiveTruths** [kdave/btrfs-progs#540]
Hey again, defrag has been quite noisy in btrfs-progs-6.

If I'm understanding the pr_verbose stuff, then I think this is bug.

Previously (<6) calling btrfs fi de -r /home would not return anything.

Now calling btrfs fi de -r /home will return each file as it's defrag'd.

You can get the old behaviour with btrfs -q fi de -r /home.

Means people running scripts that defrag might get a big ol' list of their files in their log, which is why I noticed the new behaviour.

**Comment by kdave** [comment]
Thanks for noticing it, that's a regression.

**Comment by kdave** [comment]
Fixed in devel.
