### ISSUE TITLE
`btrfs filesystem mkswapfile --help` shows wrong text

### ISSUE THREAD

**Issue by Winterhuman** [kdave/btrfs-progs#554]
Currently, `btrfs filesystem mkswapfile --help` shows:

```
usage: btrfs filesystem mkswapfile <file>

    Force a sync on a filesystem

    Global options:
    -v|--verbose       increase output verbosity
    -q|--quiet         print only errors
```

I don't know if this is already corrected in the btrfs-devel patches set for btrfs-progs v6.1, feel free to close this issue if this is a known, temporary thing until then

**Comment by kdave** [comment]
Thanks for the report, now fixed in devel.
