### ISSUE TITLE
Implement json output for qgroup show

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#555]
The text output of `qgroup show` is parsed by https://github.com/openSUSE/libstorage-ng but this is causing problems when it's updated. Implement the json format.

**Comment by kdave** [comment]
For preview pushed to branch `dev/qgroup-show-json` with example output in the commit log.

**Comment by kdave** [comment]
@aschnell Re: https://github.com/openSUSE/libstorage-ng/pull/907 please let me know if the proposed json output is OK.

**Comment by aschnell** [comment]
The the example the "max_referenced" is "0": Does that mean no limit or a limit of 0? I would suggest to set it to "" or omit it if there is no limit.

Other fields could also be omitted, e.g. parent, if empty.

And that is the layout of the version? Will it be "1.1" when something gets add? Will it be "2" if there is a incompatible change?

**Comment by kdave** [comment]
The limits should be consistent with the text output, so in the json output 0 means limit is zero, 'none' if there's no limit. I forgot to check the flag if the value is set so there's 0. I'd rather print the key:value even if the value has some special meaning rather than making it optional.

The versions are meant to be only integer values, so far there was no need to deal with compatibility, the header is there "just in case". I can't tell if it would be always forward compatible, ie. implemented parser of v1 will also be readable by v2 unchanged.

**Comment by aschnell** [comment]
OK, I think libstorage-ng will then not look at the version number for the time being. It will report errors if it cannot find the fields it needs.

**Comment by kdave** [comment]
Adding new fields should be backward compatible, changes like type from value to list would be incompatible and would need version bump but this could still be solved by adding a new key with some suffix. I found that json also support schemas so commands with json output would have the schema defined in a separate so exernal software can use that. 

Thanks for the feedback, the code is now in devel, target release 6.1.
