### ISSUE TITLE
Docs say the default space_cache version is v1

### ISSUE THREAD

**Issue by TheSiman** [kdave/btrfs-progs#560]
Hi, I was under the impression that space_cache=v2 is the default now, also supported by #295. But quoting the [docs](https://btrfs.readthedocs.io/en/latest/Administration.html):

> (nospace_cache since: 3.2, space_cache=v1 and space_cache=v2 since 4.5, **default: space_cache=v1**)

> The original one, referred to as **v1, is the safe default**.

and

> If a version is not explicitly specified, the **default implementation** will be chosen, which is **v1**.

I get the impression that it's...not? Am I reading the docs wrong or were they just never updated to reflect this change?

**Comment by kdave** [comment]
Thanks for the report, the docs are out of date and need to be fixed.

**Comment by kdave** [comment]
Fixed in devel.
