### ISSUE TITLE
UUID is empty in subvolume list 

### ISSUE THREAD

**Issue by ccat3z** [kdave/btrfs-progs#562]
UUID is empty in subvolume list after d729048be6ef072bf2de76442e059af00bd1db8a. Test on linux 6.0.12 (ArchLinux).

```
$ sudo ./btrfs subvolume list -a -u '/mnt/volume'
ID 333 gen 1434028 top level 5 uuid -                                    path a
ID 335 gen 1434109 top level 5 uuid -                                    path b
ID 337 gen 1433478 top level 5 uuid -                                    path c
ID 338 gen 1434124 top level 5 uuid -                                    path d
ID 339 gen 1432646 top level 5 uuid -                                    path e
```

**Comment by Conan-Kudo** [comment]
Reported also in Fedora: [rhbz#2156710](https://bugzilla.redhat.com/2156710)

**Comment by joshuataylor** [comment]
Sorry to add to this post, but if you use ArchLinux, you can do the following:

1. Check what version of `btrfs-progs` you currently have:
```bash
pacman -Qi btrfs-progs | grep Version
```
> Version         : 6.1-1.1

2. For x86_64, download https://archive.archlinux.org/repos/2022/12/20/core/os/x86_64/btrfs-progs-6.0.2-1-x86_64.pkg.tar.zst
> Note: This might also be in your `/var/cache/pacman/pkg/` directory already.

3. `pacman -U btrfs-progs-6.0.2-1-x86_64.pkg.tar.zst`

4. Open `/etc/pacman.conf` and add `btrfs-progs` to `IgnorePkg`, so it won't be upgraded next time you update using your package manager. When this is fixed, you can simply remove it from ignorepkgs.

**Comment by tdolega** [comment]
> if you use ArchLinux
they patched it now, you can safely upgrade to 6.1-2

**Comment by kdave** [comment]
Fix pushed to devel. This bug as a high impact so there will be a hotfix release in a few days.

**Comment by kdave** [comment]
v6.1.1 released.
