### ISSUE TITLE
6.1.1 still breaks build of docker-20.10.22

### ISSUE THREAD

**Issue by hhoffstaette** [kdave/btrfs-progs#566]
The recently reverted changes (6.1 -> 6.1.1) were apparently not sufficient.

I just tried to build docker-20.10.22 on Gentoo with btrfs-progs-6.1.1 installed and got:
```
---> Making bundle: dynbinary (in bundles/dynbinary)
Building: bundles/dynbinary-daemon/dockerd-20.10.22
GOOS="" GOARCH="" GOARM=""
# github.com/docker/docker/daemon/graphdriver/btrfs
daemon/graphdriver/btrfs/btrfs.go:437:11: args.lim.max_referenced undefined (type _Ctype_struct_btrfs_qgroup_limit has no field or method max_referenced)
 * ERROR: app-containers/docker-20.10.22::gentoo failed (compile phase):
 *   dynbinary failed
```
After temporarily downgrading btrfs-progs to 6.0.2 docker built correctly.
This is curious because as far as I can see docker-20.10.22 was tagged before any btrfs changes were merged into that branch.

**Comment by berndf** [comment]
Yes, just discussing a scopeo build failure with 6.1.1 in https://bugs.gentoo.org/888579
Point is that ioctl.h exists twice in the btrfs-progs sources - once on top level and once below libbtrfs/. The latter was not patched in the revert https://github.com/kdave/btrfs-progs/commit/e78fe2d92e75ef6655341a5f498891c5b3091cb7 but gets installed to /usr/include/btrfs, breaking the build of external software.

**Comment by hhoffstaette** [comment]
![image](https://user-images.githubusercontent.com/499973/210547352-74b7e6e0-eaa6-4643-bac9-c6f73cf8ad94.png)

**Comment by kdave** [comment]
Fixes pushed to devel, I did first build tests and all pass. https://build.opensuse.org/project/monitor/home:dsterba:btrfs so far only the i586 builds finished, not sure why x86_64 haven't started. I'd appreciate if somebody else can double check that this time the fixes will be complete.

**Comment by berndf** [comment]
I can confirm that app-containers/skopeo-1.10.0-r1 compiles without needing patches against sys-fs/btrfs-progs-6.1.1 plus the above https://github.com/kdave/btrfs-progs/commit/27bb4f6819df6ad7771e089e1fd3f1bd1163e437

**Comment by hhoffstaette** [comment]
I've dropped the patch into the btrfs-pogs build, reinstallde and docker-20.10.22 rebuilt correctly. :tada:

**Comment by kdave** [comment]
Thanks, 6.1.2 about to be released.
