### ISSUE TITLE
Confusion about btrfs-progs log output

### ISSUE THREAD

**Issue by zhanglikernel** [kdave/btrfs-progs#570]
btrfs-progs uses the pr_verbose function to print different levels of logs, 
but how do we change the log level we want to print, it seems that we should use the -v
option to gradually increase the log level,
for example, if I want to print debug level information, I should use global option -v 4 times

```
btrfs -v -v -v -v <command>
```

Because of the code below, bconf.verbose is
incremented by 1 each time it is involved.

```
void bconf_be_verbose(void)
{
          if (bconf.verbose == BTRFS_BCONF_UNSET)
                  bconf.verbose = 1;
          other
                  bconf.verbose++;
}
```

But usually, if I want to print debug information, I
prefer to have a very precise log level in the command, such as printing debug information,
use the following command. 

```
btrfs --debug <command>
```

thanks
Li

**Comment by adam900710** [comment]
`-vvv` is a pretty common usage, just check `curl`.

Thus I don't think this is any problem.

**Comment by kdave** [comment]
An option to select the exact level can be added, something like `btrfs --log=debug command`.

**Comment by kdave** [comment]
Now implemented in devel.
