### ISSUE TITLE
Enhancement: trim when reducing fs size 

### ISSUE THREAD

**Issue by Forza-tng** [kdave/btrfs-progs#578]
Btrfs should issue a trim/unmap command when reducing the filesystem on a device that supports trim.

```
# btrfs fi resize 1:-1G /
Resize device id 1 (/dev/nvme0n1p5) from 203.89GiB to 202.89GiB
```

**Comment by kdave** [comment]
The `discard=async` that's been on by default for some time (6.2+) does that (and more). Deleted block groups get trimmed, resize reducing size deletes the block groups. There may be a delay between deletion and trimming but otherwise I think this works.

**Comment by Forza-tng** [comment]
Thanks. I dont always use discard=async, so I will have to remember to enable discard=async before doing resize next time.

**Comment by kdave** [comment]
The resize interface is a bit different than other ioctls and we can't pass flags easily, i.e. user can't say "I want trim after resizing" or not (assuming there could be a case to not run on such device). The async discard is a workaround but at least it can be a choice done by user, in case it's not enabled by default.
