### ISSUE TITLE
Omit setting a UUID when creating a swapfile

### ISSUE THREAD

**Issue by nl6720** [kdave/btrfs-progs#581]
`btrfs filesystem mkswapfile` creates a swap file with a UUID, but you can't really reference a swapfile by its UUID anywhere, so it is basically useless. How about _omiting it_ entirely?

[`mkswap` implemented `-U clear` ](https://github.com/util-linux/util-linux/commit/54ef08ed37acce099035cc6da7a3bdce63b00e3a) some time ago, which effectively sets it to `00000000-0000-0000-0000-000000000000`. So `btrfs filesystem mkswapfile` would need to do something similar.

**Comment by kdave** [comment]
Sure, the --uuid/-U option can be copied from mkswap, with the same values.

**Comment by kdave** [comment]
Added to devel.
