### ISSUE TITLE
6.2 release tarballs still have config.h.in in topdir, not include dir

### ISSUE THREAD

**Issue by pierre-labastie** [kdave/btrfs-progs#583]
The error shows up at the end of configure:
```
configure: creating ./config.status
config.status: creating Makefile.inc
config.status: creating Documentation/Makefile
config.status: creating libbtrfs/version.h
config.status: creating libbtrfsutil/libbtrfsutil.pc
config.status: error: cannot find input file: `include/config.h.in'
```
Note that running `./autogen.sh` generates config.h.in into the right directory, and allows to build the package

**Comment by kdave** [comment]
Yeah, if you run it from the same git directory as before you need to run autogen.sh. I've tested a clean git checkout, autogen, configure, make that it works.

**Comment by kdave** [comment]
Oh I misread it, the tarballs are wrong.

**Comment by kdave** [comment]
It was a bug in the release script, the files need to be added to the tarball manually as it's generated by the `git archive` command. And I've noticed another bug that the generated manual pages were not added after the switch to RST, so new tarballs will have them again. Thanks for the report.
