### ISSUE TITLE
6.2 does not build with systems libgcrypt enabled

### ISSUE THREAD

**Issue by tpowa** [kdave/btrfs-progs#586]
Hi I don't get it to build for Arch Linux with our tooling
:
btrfs-progs:        v6.2
	libbtrfs:           0.1.2 (deprecated)
	libbtrfsutil:       1.2.0

	prefix:             /usr
	exec prefix:        ${prefix}

	bindir:             ${exec_prefix}/bin
	libdir:             ${exec_prefix}/lib
	includedir:         ${prefix}/include
	pkgconfigdir:       ${libdir}/pkgconfig

	compiler:           gcc
	CFLAGS:             -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -ffile-prefix-map=/build/btrfs-progs/src=/usr/src/debug/btrfs-progs -flto=auto
	LDFLAGS:            -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -flto=auto

	programs:           yes
	shared libraries:   yes
	static libraries:   yes
	documentation:      yes
	doc generator:      sphinx
	backtrace support:  yes
	btrfs-convert:      yes (ext2,reiserfs)
	zstd support:       yes
	lzo support:        yes
	fsverity support:   yes
	Python bindings:    yes
	Python interpreter: /usr/bin/python
	crypto provider:    libgcrypt 1.8.0
	libudev:            yes
	zoned device:       yes

  [LD]     btrfs-image
/usr/bin/ld: /tmp/ccsnvVaO.ltrans4.ltrans.o: in function `hash_init_accel':
/build/btrfs-progs/src/btrfs-progs-v6.2/crypto/hash.c:26: undefined reference to `blake2_init_accel'
/usr/bin/ld: /build/btrfs-progs/src/btrfs-progs-v6.2/crypto/hash.c:27: undefined reference to `sha256_init_accel'
/usr/bin/ld: /tmp/ccsnvVaO.ltrans4.ltrans.o: in function `hash_init_blake2':
/build/btrfs-progs/src/btrfs-progs-v6.2/crypto/hash.c:37: undefined reference to `blake2_init_accel'
/usr/bin/ld: /tmp/ccsnvVaO.ltrans4.ltrans.o: in function `hash_init_sha256':
/build/btrfs-progs/src/btrfs-progs-v6.2/crypto/

Seems i'm not alone on IRC others are affected too.

**Comment by kdave** [comment]
Thanks, it's been also reported in the mailinglist and bugfix release is on the way, currently in branch devel.
