### ISSUE TITLE
btrfs-utils-6.2.1 convert-tests fails

### ISSUE THREAD

**Issue by bdubbs** [kdave/btrfs-progs#592]
Using kernel-6.1.11 multiple ./convert-tests fail.  For instance:

====== RUN CHECK /sources/btrfs-progs-v6.2.1/btrfs check /sources/btrfs-progs-v6.2.1/tests/test.img
[1/7] checking root items
[2/7] checking extents
[3/7] checking free space cache
[4/7] checking fs roots
root 5 inode 266 errors 2000, link count wrong
ERROR: errors found in fs roots
Opening filesystem to check...
Checking filesystem on /sources/btrfs-progs-v6.2.1/tests/test.img
UUID: 4dff914f-2a40-441b-bca6-48ae43cd8c86
found 177025024 bytes used, error(s) found
total csum bytes: 172912
total tree bytes: 573440
total fs tree bytes: 327680
total extent tree bytes: 36864
btree space waste bytes: 109451
file data blocks allocated: 377929728
 referenced 246542336
failed: /sources/btrfs-progs-v6.2.1/btrfs check /sources/btrfs-progs-v6.2.1/tests/test.img
test failed for case 003-ext4-basic

Essentially the same failure occurs for tests 005 and 006.

**Comment by renodr** [comment]
I can also reproduce this. If it helps, I'm running e2fsprogs-1.47.0

**Comment by bdubbs** [comment]
I downgraded to e2fsprogs-1.46.6 and TEST=003\* ./convert-tests.sh worked fine.  There is something in e2fsprogs-1.47.0 causing these failures.

**Comment by pierre-labastie** [comment]
It is the `oprhan_file` ext4 feature that has been added to mke2fs.conf at the same time as the `metadata_csum_seed` feature (commit fe341d59ee in e2fsprogs git repo), that triggers the failure.

**Comment by kdave** [comment]
Fixed by f3353a5e855c5da4ce1f2b00a8054f354e8f5d4f in 6.2.2.
