### ISSUE TITLE
Provide static version or btrfs-progs

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#593]
There's https://wiki.tnonline.net/w/Btrfs/Statically_built_btrfs-progs, we could do that in a slightly more official way and provide the resources on the github page. The build should be reproducible so build it from the CI images at least, and signed by some known key.

**Comment by kdave** [comment]
https://github.com/kdave/btrfs-progs/actions/runs/4681047503 sample github action that produces two binaries as artifacts (btrfs.static and btrfs.box.static). There are a few problems:

- unstable url, i.e. not one location to get the binaries from, multiple steps need on web or by using  API
- downloaded files are in .zip (compression cannot be disabled with upload-artifact@v3)
- permissions of the file inside .zip are lost, manual chmod needed after extraction
- artifacts can be downloaded only for logged users

I'd appreciate any advice how to fix the things or if there's a better way to provide the binaries. The final binaries would be provided after master branch is pushed, i.e. only for a release so if the release milestone is needed it can be done.

**Comment by kdave** [comment]
https://github.com/kdave/btrfs-progs/releases/tag/v6.2.2

- manually created release
- assets built by gh actions (v6.2.2 aliases by release-latest)
- manually downloaded, chmod
- manually uploaded to v6.2.2 release as assets

**Comment by kdave** [comment]
With some scripting and up-to-date `gh` tool this can be automated.

**Comment by Forza-tng** [comment]
Thank you :) 
What cflags were used to produce the static versions?

**Comment by kdave** [comment]
https://github.com/kdave/btrfs-progs/actions/runs/4694159544/jobs/8322023591 There's a separate workflow so you can check it in the logs (section Make static), example:

```
    [CC]     kernel-shared/inode.static.o
gcc -g -O1 -Wall -D_FORTIFY_SOURCE=2 -std=gnu11 -include include/config.h -DBTRFS_FLAT_INCLUDES
-D_XOPEN_SOURCE=700 -fno-strict-aliasing -fPIC -Wall -Wunused-but-set-parameter -I. -I./include
-DCRYPTOPROVIDER_BUILTIN=1 -DCOMPRESSION_LZO=1 -DCOMPRESSION_ZSTD=1 -Wno-format-truncation
-Wno-address-of-packed-member  -Wimplicit-fallthrough    -ffunction-sections -fdata-sections
-DSTATIC_BUILD -c kernel-shared/inode.c -o kernel-shared/inode.static.o 
```

**Comment by kdave** [comment]
There have been 4 releases providing the static binaries, the process is almost entirely automated, script ci/actions/update-artifacts . Considered done.
