### ISSUE TITLE
Mount a btrfs filesystem without superuser privileges

### ISSUE THREAD

**Issue by ruanformigoni** [kdave/btrfs-progs#602]
Hello,

Is there something similar to this functionality in `fuse2fs`?

```sh
fuse2fs fs.img mnt
```

**Comment by kdave** [comment]
Qu wrote a read-only FUSE module https://github.com/adam900710/btrfs-fuse

**Comment by ruanformigoni** [comment]
I needed something that would support writing, but I guess it is not available as of yet. Thanks for you help :)

**Comment by kdave** [comment]
You can open an issue at the FUSE repository, I think you won't be the only one asking for it.
