### ISSUE TITLE
clarifications about swapfile filesystem limitations

### ISSUE THREAD

**Issue by calestyo** [kdave/btrfs-progs#608]
Hey.

`btrfs(5)`’s `SWAPFILE SUPPORT` lists numerous limitations, which seem however not 100% exact respectively - having my user hat on - interesting information seems to be missing:

- Once one activates (or even just by creating) a swapfile: is this an action that cannot be undone anymore? In the sense of even if I deactivate the swapfile again and remove it, ... will there still be limitations in place (e.g. not being able to convert to raid)?<br>Even if the answer is "no" for the whole filesystem, the same question would be interesting on a per subvolume level, in the sense of: once a subvolume has seen a swapfile, can that be undone, so that e.g. snapshots/etc. are possible again. Or can "undoing" be just done by deleting the subvolume?

- There is some vagueness in the terms swapfile (as the plain file created e.g. my mkswap) and an actually active swap area on top of that file.<br>For example, the manpage says: `swapfile - the containing subvolume cannot be snapshotted`<br>AFAICS, this is however only true for active swapfiles. I can very well deactivate the swap, and then snapshot it.<br>However - and this doesn't seem to be mentioned either - doing so, "destroys" the swapfile (trying to activate it gives a kernel warning that a CoW file cannot be a swapfile (which makes of course sense).... but may not be directly clear to users.<br>It also seems that once all snapshots are deleted, one can again create a new swapfile on the device.

Cheers,
Chris.

**Comment by kdave** [comment]
Good questions, thanks. The term swapfile is used but depending on context means an active swapfile or just the bare file, so this should be clarified. My updates are in ea7d3938c301ff133830f7aa7f6e7721bc24ad0f, let me know if there's something more to clarify.

**Comment by calestyo** [comment]
I made some comments to the commit ... pick as you like. :-)

**Comment by kdave** [comment]
Thanks, updated and pushed.

**Comment by calestyo** [comment]
I found indeed some more.

If it helps you if I make a PR with everything in once, just tell me.

**Comment by kdave** [comment]
A PR would be best, thanks.
