### ISSUE TITLE
btrfs bal can, can't

### ISSUE THREAD

**Issue by CorrosiveTruths** [kdave/btrfs-progs#612]
Not sure what's happening here, can't use the shortened form of balance cancel in latest stable? The message is a little odd too, it's treating the shortened can as a path for a deprecated version of calling it?

btrfs-progs-6.1.3

btrfs bal can /
ERROR: balance cancel on '/' failed: Not in progress

btrfs-progs-6.2.2

btrfs bal can /
WARNING: deprecated syntax, please use 'btrfs balance start'
ERROR: cannot access 'can': No such file or directory

**Comment by kdave** [comment]
Thanks for the report, it's a bug introduced by 6f7151f4992bc2a22a4fb84e7536a8b3c709a771, the condition should check for exactly 2 parameters (i.e. the old syntax), not `>= 2`.

**Comment by kdave** [comment]
Fixed in devel.
