### ISSUE TITLE
Update docs to reflect new discard=async default

### ISSUE THREAD

**Issue by neitsab** [kdave/btrfs-progs#617]
In the same vein as #560 which was just fixed, [Documentation/ch-mount-options.rst](https://github.com/kdave/btrfs-progs/blob/master/Documentation/ch-mount-options.rst#L194) should be updated to match the [new 6.2 discard=async default](https://github.com/kdave/btrfs-progs/blob/cde5faa6787e6fa720c99d2f10caa187a493c13f/Documentation/Feature-by-version.rst#L526).

Thank you for your work!

**Comment by kdave** [comment]
Fixed in devel, thanks.
