### ISSUE TITLE
How to get started development docs page has all broken links.

### ISSUE THREAD

**Issue by alastor-erinyes** [kdave/btrfs-progs#628]
All the links in this paragraph are broken: https://github.com/kdave/btrfs-progs/blob/master/Documentation/dev/Developer-s-FAQ.rst#how-to-get-started---development.

I'm happy to contribute a PR fixing them, but I don't know where they've moved to.

**Comment by kdave** [comment]
I think the link targes do not have the corresponding RTD page yet, the wiki conversion is still ongoing, but thanks for the report I'll take a look. The developer/contributor pages should be usable.

**Comment by kdave** [comment]
Updated page pushed to devel, will appear on RTD shortly. Some links have been removed, the Devloper documentation is referenced from the main index and I don't know how to create link directly to the section.
