### ISSUE TITLE
feature request: btrfs-progs dry run option

### ISSUE THREAD

**Issue by pavelskipenes** [kdave/btrfs-progs#629]
Can a global dry run option be added?
Example `btrfs --dry-run subvolume delete --subvolid [list of subvolumes] `

**Comment by kdave** [comment]
I'm not sure global option for that is a good idea. All commands would have to support it and in some cases it could be tricky (or irrelevant for commands without any external effects). I'd rather add it per command. The global options are a bit unintuitive so the idea is to add only something that applies to all commands (like verbosity, logging, output).

**Comment by kdave** [comment]
What if `--dry-run` would be available for all commands but if not implemented the command would fail right away? That could make it be a global option, ie. a standardized place but the support would depend. For some commands it should be relatively easy to implement it, the rest will simply fail.

**Comment by kdave** [comment]
The global option is now implemented and for `subvolume delete` in particular. If a command does not show the `--dry-run` in the help text it's not supported and it will fail if if the option is passed.

Adding support for dry-run mode will have to be done one by one, it affects the code flow and with some option combinations or functionality it's not straightfoward.
