### ISSUE TITLE
mkfs.btrfs fails on s390, possible endianness error

### ISSUE THREAD

**Issue by cmurf** [kdave/btrfs-progs#639]
Downstream [Bug 2214522](https://bugzilla.redhat.com/show_bug.cgi?id=2214522) - Fedora 37: mkfs.btrfs fails on s390 with btrfs-progs 6.3.1 release

```
# mkfs.btrfs /dev/dasdd1
btrfs-progs v6.3.1
See https://btrfs.readthedocs.io/ for more information.

ERROR: superblock magic doesn't match
NOTE: several default settings have changed in version 5.15, please make sure
      this does not affect your deployments:
      - DUP for metadata (-m dup)
      - enabled no-holes (-O no-holes)
      - enabled free-space-tree (-R free-space-tree)

Invalid mapping for 1081344-1097728, got 17592186044416-17592190238720
Couldn't map the block 1081344
ERROR: cannot read chunk root
ERROR: open ctree failed
```

System: Fedora 37
Fails on both 6.3 and 6.4 kernels.

**Comment by cmurf** [comment]
We didn't build btrfs-progs 6.3 in Fedora so it could be a regression in 6.3 or 6.3.1.

**Comment by sharkcz** [comment]
I am going to bisect it, easily reproduced with `make test` on a s390x machine. Unless someone beats me being faster :-)

**Comment by adam900710** [comment]
Mind to give me the access to an s390x system?
You can contact me through wqu@suse.com.

**Comment by sharkcz** [comment]
You might use `AC_BIGENDIAN` if autotools are being used or rely on the compiler and `__BYTE_ORDER__` being `__ORDER_LITTLE_ENDIAN__` or `__ORDER_BIG_ENDIAN__`. There are some guides online about the right detection procedures.

**Comment by adam900710** [comment]
I found `<bits/endian.h>` from glibc providing all the endianness checks, thus I would go `__BYTE_ORDER` checks against `__LITTLE_ENDIAN` to send the proper fix.

The synced `accessor.h` is using the kernel endianness check, which doesn't work with user space headers.

**Comment by kdave** [comment]
kerncompat.h or kernel-lib/bitops.h use `bitops.h:#if __BYTE_ORDER == __BIG_ENDIAN`

**Comment by sharkcz** [comment]
> The header is the copy from kernel so we need to use a check that's compatible on the source level, so the autoconf WORD_BIGENDIAN is not suitable here.

yes, it makes sense, thanks
