### ISSUE TITLE
document that subvols ob snapshotted subvols remain as empty un-unusable directory

### ISSUE THREAD

**Issue by calestyo** [kdave/btrfs-progs#644]
Hey.

I think it would be nice to document in `btrfs(5)` the speciality that when having e.g.
```
…/subvol1/subvol2
```
and `subvol1` is snapshotted, `subvol2` remains in the created snapshot as empty but unusable directory, i.e. one cannot create files within it.<br>
And perhaps also describe, that such – Andrei named them "orphan subvolume graft point" on the mailing list[0] – won't get send | received.

I could in principle provide a patch for that, but right now we don't have a section about snapshots or subvols, yet, so I wasn't really sure where you'd want to have such documentation.<br>
If you can tell me how you'd like to have this, I could try to make a PR.

Cheers,
Chris.

[0] https://lore.kernel.org/linux-btrfs/ea6099a3cff73c20da032afaaeb446c0b12ec1da.camel@scientia.org/

**Comment by kdave** [comment]
The manual page in section 5 covers topics that don't have separate pages, the empty subvolumes are described in btrfs-subvolume manual page (or the RTD/Subvolumes page). I've added an example how the nested subvolumes and snapshotting works, also mentioned the send/receive implications.
