### ISSUE TITLE
Illegal instruction: Upgrading from btrfs-progs-6.3.3  to btrfs-progs-6.5 broke "send/recieve" and "check" functionality

### ISSUE THREAD

**Issue by vvxvv** [kdave/btrfs-progs#676]
btrfs filesystem show /dev/sda1
> Illegal instruction

btrfs check /dev/sda1
>Opening filesystem to check... 
Illegal instruction

Journal:
>Sep 10 13:20:24 pc kernel: traps: btrfs[1491] **trap invalid opcode ip:55a7d4989eb0 sp:7ffd40934f60 error:0 in btrfs[55a7d48b5000+d6000]**
Sep 10 13:20:24 pc systemd[1]: Created slice Slice /system/systemd-coredump.
Sep 10 13:20:24 pc systemd[1]: Started Process Core Dump (PID 1492/UID 0).
Sep 10 13:20:24 pc systemd-coredump[1493]: Resource limits disable core dumping for process 1491 (btrfs).
Sep 10 13:20:24 pc systemd-coredump[1493]: [🡕] Process 1491 (btrfs) of user 0 dumped core.
Sep 10 13:20:24 pc sudo[1489]: pam_unix(sudo:session): session closed for user root
Sep 10 13:20:24 pc systemd[1]: systemd-coredump@0-1492-0.service: Deactivated successfully.

uname -a
>Linux pc 6.1.52-1-lts #1 SMP PREEMPT_DYNAMIC Thu, 07 Sep 2023 05:17:41 +0000 x86_64 GNU/Linux
 Arch Linux

PS: Downgrading back to the 6.3.3 solves the problem

**Comment by kdave** [comment]
This must be because of the updated accelerated crc32c but it's using the same CPU instructions so there should not be any change. What CPU family/model is it?

**Comment by vvxvv** [comment]
└─⮞ ./hash-speedtest 

> CPU flags: 0x1f
> CPU features: SSE2 SSSE3 SSE41 SSE42
> Block size:     4096
> Iterations:     100000
> Implementation: builtin
> Units:          CPU cycles
> 
>    NULL-NOP: cycles:     43087904, cycles/i      430
>    NULL-MEMCPY: cycles:     82190620, cycles/i      821,    19042.311 MiB/s
>    CRC32C-ref: cycles:   3740497124, cycles/i    37404,      418.434 MiB/s
>    CRC32C-NI: Illegal instruction (core dumped)

**Comment by kdave** [comment]
> Does not contain pclmulqdq.

Right, thanks. That's it and needs to be tested separately from the SSE flags.

**Comment by vvxvv** [comment]
loqs, kdave thanks

**Comment by kdave** [comment]
Can you please test if v6.5.x fixes the problem on your side? I have verified build but don't have a proper 32bit environment without the PCLMUL support.

**Comment by vvxvv** [comment]
**Kdave**, Yes, the problem is fixed!

**Comment by kdave** [comment]
Thanks.
