### ISSUE TITLE
mkfs.btrfs incompatible with PR_SET_MDWE when built with a compiler that was built with --enable-default-pie

### ISSUE THREAD

**Issue by loqs** [kdave/btrfs-progs#678]
btrfs-progs 6.5
systemd 254.3

Systemd service hardening [1] detected btrfs.fsck as built by Arch Linux [2] uses memory that is both writable and executable.  This is due to the interaction between -pie which gcc as provided by Arch has auto enabled and https://github.com/kdave/btrfs-progs/blob/f7ecc34555b4793573c9e3fc5f77cc8aab63fcc1/crypto/crc32c-pcl-intel-asm_64.S#L324
The code which I believe originated in the kernel builds with  -no-pie so such an issue is not present there.  There is also no benefit to using PIE in the kernel.  Changing the section from .rodata to .data resolves the issue and keeps PIE.

[1]: https://github.com/systemd/systemd/issues/29160
[2]: https://bugs.archlinux.org/task/79654

**Comment by kdave** [comment]
Changing it from `.rodata` to `.data` gives a warning:

```
crypto/crc32c-pcl-intel-asm_64.S: Assembler messages:
crypto/crc32c-pcl-intel-asm_64.S:343: Warning: ignoring changed section attributes for .data
```

**Comment by kdave** [comment]
This is after change done in 839b2d587da9d691c (#675) .

**Comment by loqs** [comment]
Adding https://github.com/kdave/btrfs-progs/commit/839b2d587da9d691c2f2e7cdb5301eed23781d1d fixes the issue.
Do you think it is safe to cherry-pick just that commit?

**Comment by kdave** [comment]
I think it's safe but I'm not sure it works for the PIE build, the fix was for relro.

**Comment by loqs** [comment]
I think the root cause in both issues was the symbol relocations.
I have asked for confirmation that the issue is fixed in [1].

[1] https://bugs.archlinux.org/task/79654#comment221989

**Comment by kdave** [comment]
I can now reproduce the systemd problem and have verified that PIE build works with the systemd-run command with hardening:

```
$ make EXTRA_CFLAGS='-pie -fPIE' EXTRA_LDFLAGS='-pie -fPIE' -j mkfs.btrfs
$ readef -h mkfs.btrfs
Type: "DYN (Position-Independent Executable file)"
$ systemd-run -t -p MemoryDenyWriteExecute=yes ./mkfs.btrfs
... mkfs default output
````

With the commit "btrfs-progs: crypto: fix readonly relocation of the jumptable".

**Comment by loqs** [comment]
Fixed by https://github.com/kdave/btrfs-progs/commit/839b2d587da9d691c2f2e7cdb5301eed23781d1d

**Comment by loqs** [comment]
Fixed by https://github.com/kdave/btrfs-progs/commit/839b2d587da9d691c2f2e7cdb5301eed23781d1d
