### ISSUE TITLE
Add tests and docs for raid-stripe-tree

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#679]
The raid-stripe-tree is in kernel queu and progs have the support.

- [x] add mkfs tests
- [x] add design document to our documentation

**Comment by kdave** [comment]
https://docs.google.com/document/d/1Iui_jMidCd4MVBNSSLXRfO7p5KmvnoQL/edit

**Comment by CorrosiveTruths** [comment]
Hi @kdave, sorry for the noise, but would this raid-stripe-tree make it possible to re-balance raid1 data paired on specific devices (if balance was enhanced to support such)? Like re-balance raid1 data that is on paired on device 2&4 only?

**Comment by Zygo** [comment]
> Like re-balance raid1 data that is on paired on device 2&4 only?

This is already possible and can be implemented in python-btrfs.  Search the chunk tree, find each chunk that has a stripe 2 and 4, make a list of the vaddrs of the chunks.   Then balance each chunk with the `vaddr` filter.

A balance filter for "every device _except_ this one" (i.e. a negative `devid` filter) would be very handy for upgrading one disk in a raid1 array.

**Comment by CorrosiveTruths** [comment]
Thanks for the pointer, @Zygo, mucking about with fs.chunks from python-btrfs now; seems to be able to do exactly what I wanted.

**Comment by kdave** [comment]
The question tracked in another issue, if there's something we can do outside of python-btrfs.
