### ISSUE TITLE
--rootdir does not copy xattrs from the root directory

### ISSUE THREAD

**Issue by DaanDeMeyer** [kdave/btrfs-progs#688]
After booting into an filesystem generated with btrfs-progs --rootdir:

```
[root@fedora ~]# getfattr -dm- /usr
getfattr: Removing leading '/' from absolute path names
# file: usr
security.selinux="system_u:object_r:usr_t:s0"

[root@fedora ~]# getfattr -dm- /
```

It seems as if the `traverse_directory()` simply does not call `add_xattr_item()` for the root directory so the root directory does not have any of its xattrs in the generated filesystem.

**Comment by adam900710** [comment]
Indeed, the root directory needs one dedicated call for the xattr items.

Would fix it soon.

**Comment by DaanDeMeyer** [comment]
@adam900710 I haven't checked but is the permissions mode from the source directory applied correctly? I figure if the xattr's aren't handled correctly, the permissions might not be handled correctly either.

**Comment by adam900710** [comment]
Right, I'll take a deeper look into what's missing for the rootdir.

**Comment by DaanDeMeyer** [comment]
@adam900710 Any chance you could take a stab at https://github.com/kdave/btrfs-progs/issues/42 as well? Having a --subvol option to indicate that certain directories in the user provided root directory should become subvolumes in the generated filesystem would make mkfs.btrfs much more useful.

**Comment by adam900710** [comment]
Sure, it looks simple enough.

**Comment by kdave** [comment]
Xattrs for rootdir are fixed in devel. Regarding the --subvol and #42, we'll continue there.
