### ISSUE TITLE
btrfs-progs 6.6 tarballs refer to version 6.5.3

### ISSUE THREAD

**Issue by jpalus** [kdave/btrfs-progs#703]
Just noticed announcement on linux-btrfs about btrfs-progs 6.6 however tarballs available at: https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/ still mention version 6.5.3 including `VERSION` file in top level directory.

**Comment by kdave** [comment]
Looks like the tarball is really 6.5.3, no 6.6 changes in the CHANGES file.

**Comment by kdave** [comment]
Thanks for noticing it, this was due to changes in directory structure on the release machine. Correct v6.6 are now at https://www.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/

Timestamp: 03-Nov-2023 20:14

```
d40af9e8c8bb7499450503e8d1f494b9f1ef1b8762d1c32ea4873b7bab4335f5 btrfs-progs-v6.6.tar.gz
96792995eefb2eaae051c2ce3b5609b7e9bb2c1a5cb83fe69f92f1101b54b869 btrfs-progs-v6.6.tar.xz
```

**Comment by jpalus** [comment]
Thanks!
