### ISSUE TITLE
Unable to mount RAID 1 drive using v6.6 btrfs.box.static

### ISSUE THREAD

**Issue by Oldlostcoder** [kdave/btrfs-progs#704]
On Kernel 6.1.61; with RAID 1 drives there seems to be an issue with v6.6 btrfs.box.static device scan.  The command registers the drives but they do not mount.  Using v6.5.3 btrfs.box.static; mounting works.  Not sure if this is a bug, or Kernel 6.1.61 is not compatible with v6.6.

**Comment by kdave** [comment]
I saw such problems in the github CI and it was related to loop devices, do you use them or are the block devices disk/ssd/nvme/...?

**Comment by kdave** [comment]
I've tried that on a few nvme devices, seems to work.

**Comment by adam900710** [comment]
Any dmesg for the mount failure (and the device scan lines before that)?

**Comment by adam900710** [comment]
Thanks, I believe your output from 2) is already showing something wrong with the device scan.

`mkfs.btrfs` would try to register the devices to make then work, the register part is shared between all btrfs-progs.
If that devices registration doesn't work, no wonder later mount would fail.

Unfortunately I failed to reproduce using the same v6.6, although not static build, as my distro doesn't provide static libraries anymore.

Have you tried compiling btrfs-progs from scratch? Both static and dynamic linked version, to see how things would change?

**Comment by adam900710** [comment]
Just curious, can I get the precompiled statically linked btrfs-progs you're using?

**Comment by thesamesam** [comment]
This might be fixed by https://github.com/kdave/btrfs-progs/pull/706.

**Comment by adam900710** [comment]
Oh, that's indeed a regression, the scan ioctl is bounded to forget instead...

**Comment by kdave** [comment]
Fixed in v6.6.1, thanks for the report.
