### ISSUE TITLE
6.6.2 -- "_FORTIFY_SOURCE" redefined

### ISSUE THREAD

**Issue by pomac303** [kdave/btrfs-progs#715]
<command-line>: warning: "_FORTIFY_SOURCE" redefined
<built-in>: note: this is the location of the previous definition

For every C file being compiled... - removing the -D_FORTIFY_SOURCE=2 in Makefile.inc removes the notice, but would that be correct?

**Comment by kdave** [comment]
Do you pass any other flags to configure or make? The fortify options are there as some sane defaults and distros usually set their own which override that, provided that the CFLAGS are set at configure time.

**Comment by pomac303** [comment]
No... not really, seems like it was a older gcc version, I have since switched to gcc 13, so you can colse this, sorry for the noise

**Comment by pomac303** [comment]
Oh, there is a shiny button for me! closing, old gcc - nothing to be fixed.
