### ISSUE TITLE
 FEATURE REQUEST: add option avoid looping question

### ISSUE THREAD

**Issue by FransM** [kdave/btrfs-progs#745]
needed to restore a large volume with btrfs restore
For several files it asked
"We seem to be looping a lot on , do you want to keep going on ? (y/N/a):"
Now while entering 'athe question is suppressed for the current file, but it would be nice to have an option or an answer to suppress it totally.

Rationale: a large disk restore can take several hours and the user might not be at the screen all the time.

Workaround I used: yes | btrfs restore ....
but I feel it would be better to have this as an option (or as a possible answer the first time this question pops up.

**Comment by kdave** [comment]
Which version do you use? This was removed 2 years ago in 4258b7161fa8a9c9a9f9a3ba912d796b1a1afd24 v5.13.

**Comment by FransM** [comment]
Ah ok, then I suspect this can be closed.
I was using the version provided with Ubuntu 20.04.6 LTS
This one identifes as v5.4.1
