### ISSUE TITLE
Feature request: Make `btrfs` file name shorter to increase type speed

### ISSUE THREAD

**Issue by moontide** [kdave/btrfs-progs#755]
When type '`btrfs`' using US keyboard layout, left index finger will move 4 times to enter `b` `t` `r` `f` (across long distance), this will slow down type speed slightly (compare to typing '`zfs`').

Currently, I created a symbolic link to `/usr/bin/btrfs` as a workaround.

I wish btrfs-progs can provide an official short version (in three letters) of '`btrfs`' file name, and avoid characters from left finger's ranges for the first character.

**Comment by ErrorNoInternet** [comment]
Why not a shell alias?

**Comment by moontide** [comment]
> Why not a shell alias?

Shell alias, or symbolic link, are all good.

Using shell alias or symbolic links, I can name it to whatever I wanted, but, it's not portable, nor been knowable -- I mean, if someone saw `cfs list`, he/she does not know what `cfs` is. `c` is came from `CoW`, but it seems it not a proper short name for btrfs, because there are other CoW file systems too. A short name came from official would be more suitable.

**Comment by kdave** [comment]
This sounds beyond what we can provide, it's a personal preference and it's easily solvable by aliases and convenience scripts. Shell completion would have to be updated to work with the short name. Shorter names could be confusing, bfs, or btr. You're right that typing the word by one hand and even 4/5 by one finger is slow, though you can speed up by typing the `tr` by index and middle fingers, and `fs` by index + ring f.

**Comment by kdave** [comment]
So if you want to use the completion with a custom script name, you can do:

```
source /usr/share/bash-completion/completions/btrfs
complete -F _btrfs bb
```

where `bb` is name of your script. We can add it to documentation but I'm not sure how many people would use that.
