### ISSUE TITLE
Add support for running the tools from a given path

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#77]
... (git, /usr/bin, /usr/local/bin), so the testsuite can be run independently.

The idea is to export the testsuite files to a separate tar, run from a script. In that case the system binaries will be preferred.

This is supposed to extend the testing possibilities. The packaging phase could run some tests, many tools run post-build tests, but we need to manage devices and require root in general. This is not always possible, besides that it requires to run from the sources directory.

**Comment by gujx2017** [comment]
I have send a RFC v2, and you can also get it from:
https://github.com/gujx2017/btrfs-progs/tree/export_testsuites

**Comment by kdave** [comment]
Commented in the mailinglist, v2 is not in a shape to be merged.

**Comment by kdave** [comment]
Patches merged, with followups. Closing.
