### ISSUE TITLE
`qgroup destroy`: warn if qgroup cannot be removed after subvolume deletion

### ISSUE THREAD

**Issue by kdave** [kdave/btrfs-progs#782]
Removing a stale qgroup may not succeed for several reasons:

https://lore.kernel.org/linux-btrfs/fa8f65936f31c07ca4783229140ecfb1f7ada785.1714082499.git.wqu@suse.com/ :

- Currently kernel doesn not allow to delete non-empty qgroups
- A qgroup can only be empty after fully dropped and a transaction is committed
- Things like drop_subtree_threshold or other operations can mark qgroup inconsistent and skip accounting

The option --delete-qgroup has been removed but the same can happen with `btrfs qgroup destroy` as it's the same implementation by an ioctl.

We need to catch the conditions preventing the deletion and warn, or add options that will try to do the right thing at some cost, like waiting until the subvolume is cleaned.

**Comment by adam900710** [comment]
This sounds very reasonable and would be much more user friendly.

I'll add this feature soon.

**Comment by kdave** [comment]
Seems to be fixed by 82f7d6c1d711c1c50a5c2bfc31fca92635a92cdf, also needs the kernel fixes.
