### ISSUE TITLE
`receive --dump` doesn't escape some outputs

### ISSUE THREAD

**Issue by bmillwood** [kdave/btrfs-progs#818]
The ones I ran into are the `from` parameter in `clone` ([code](https://github.com/kdave/btrfs-progs/blob/87c7821d528448ffd387c38725308c75bd504120/cmds/receive-dump.c#L258C19-L258C28)), and `data` for `set_xattr`. Maybe xattr names also strictly speaking need to be escaped?

This makes it impossible to perfectly parse `receive --dump` programmatically because paths can contain whitespace and equals signs, and some xattr values on my system even contain newline characters.

It looks like this is already handled for some other commands, by using `PRINT_DUMP_NO_NEWLINE` and then `print_path_escaped`, so I bet this would be a pretty easy fix. (I could possibly do it myself but I'm hoping to avoid all the overhead of learning how to compile and test this stuff for the first time :) )

**Comment by kdave** [comment]
Thanks for the report. The path in clone is indeed missing the encoding. I can't find any defined constraints for the xattr names, values can be expected to be any value so this needs to be escaped.

**Comment by kdave** [comment]
Fixed in devel.

**Comment by kdave** [comment]
Yes, that's a good point, feel free to send a patch to rename it.

**Comment by kdave** [comment]
Fix released in v6.9.1.
