### ISSUE TITLE
Question on deprecation of `--clear-space-cache v1|v2`

### ISSUE THREAD

**Issue by Forza-tng** [kdave/btrfs-progs#854]
Hi, the Changelog for [btrfs-progs 6.6](https://github.com/kdave/btrfs-progs/releases/tag/v6.6) says the clear-space-cache feature is deprecated:

>rescue clear-space-cache: new command moved from 'btrfs check' implementing the same as option --clear-space-cache (to be deprecated and removed in the future)

Does it mean that the kernel will clean out all parts of v1 cache, or just that v2 has been the default long enough, so that we eventually no longer need this conversion functionality?

**Comment by adam900710** [comment]
It just means the option "--clear-space-cache" of "btrfs check" will be deprecated.

Kernel behavior is not changed (aka, clear-space-cache mount option still only rebuild the modified block groups).

**Comment by Forza-tng** [comment]
Thank you for the explanation. Zygo mentioned on IRC the patch [btrfs: remove free space items when disabling space cache v1 ](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/fs/btrfs?id=36b216c85eb9) for 5.11 that should remove v1 bits, but maybe we still need manual cleaning?

**Comment by kdave** [comment]
This was only for command line UI cleanup, the `check` option was removed and functionality moved to `rescue` group where it will stay until everybody forgets such thing was ever needed. There are people using kernels without the fix (<5.11) so manual fix may be needed and the tool will provide it.

I see the documentation has the links from check to rescue, is there anything missing?

**Comment by Forza-tng** [comment]
I was just confused because we originally needed the clear-space-cache and it just stuck in my mind. The issue is clear for me now though. Thank you. 🙏 We can close this ticket.

**Comment by kdave** [comment]
Yes I think so, e.g. commit torvalds/linux@948462294577a3870c40 and others.
