### ISSUE TITLE
btrfs-progs devel: build failure: asciidoc: Too many arguments

### ISSUE THREAD

**Issue by Lakshmipathi** [kdave/btrfs-progs#87]
Quick bug report. Seems like devel-branch build is failing while building docs:

> Making all in Documentation
>     [ASCII]  btrfs-ioctl.xml
> asciidoc: Too many arguments
> 
> Man page:     asciidoc --help manpage
> Syntax:       asciidoc --help syntax
> make[1]: *** [Makefile:125: btrfs-ioctl.xml] Error 1
> make: *** [Makefile:294: build-Documentation] Error 2
> 
> 
Here is the [logs](https://htmlpreview.github.io/?https://github.com/Lakshmipathi/buildlogs/blob/master/Lakshmipathi/results_2018-01-26_10:58/results.html)

**Comment by kdave** [comment]
Thanks for catching it, fixed in devel, commit "btrfs-progs: build: simplify version tracking".
