### ISSUE TITLE
fsck/028-unaligned-super-dev-sizes failure report

### ISSUE THREAD

**Issue by Lakshmipathi** [kdave/btrfs-progs#88]
While running btrfs-progs/devel on latest btrfs-devel/misc-next (4.15.0-rc9), fsck/028-unaligned-super-dev-sizes  passed [last week](https://asciinema.org/a/VQ5UiWF9cYPLLigM04ea9mLlU)

Now it fails with message like:

> root_helper mount -t btrfs -o loop /home/fedora/btrfs-progs/tests/test.img /home/fedora/btrfs-progs/tests/mnt
> mount: /home/fedora/btrfs-progs/tests/mnt: wrong fs type, bad option, bad superblock on /dev/loop0, missing codepage or helper program, or other error.
> failed: root_helper mount -t btrfs -o loop /home/fedora/btrfs-progs/tests/test.img /home/fedora/btrfs-progs/tests/mnt
> test failed for case 028-unaligned-super-dev-sizes
> 

Just want to quickly update this issue, will try to narrow down the patch later this week.  build [logs](https://htmlpreview.github.io/?https://github.com/Lakshmipathi/buildlogs/blob/master/Lakshmipathi/results_2018-01-30_07:09/results.html)

**Comment by kdave** [comment]
Now fixed. CI is green a we're ready for a release.
