### ISSUE TITLE
Is compression subvol spesific or not?

### ISSUE THREAD

**Issue by SuiIntent** [kdave/btrfs-progs#880]
man btrfs(5) `Mount options` has a note where it says compression is file system wide. 
But in examples i find they assign no compression to some subvol while enabled on the root. Even though they come from the same btrfs partition. 

Is this just examples beeing confusing?

https://wiki.gentoo.org/wiki/Btrfs/Native_System_Root_Guide

Thanks in advance.

**Comment by Forza-tng** [comment]
Compression mount options are indeed applied for the whole filesystem. Any subsequent mount will inherit the compression. However, if a subsequent mount includes new compression options, those will take effect for the whole filesystem.

**Comment by SuiIntent** [comment]
Thanks!
