### ISSUE TITLE
"btrfs send -p" fails if source and parent subvolumes are on different mountpoints (memory corruption)

### ISSUE THREAD

**Issue by digint** [kdave/btrfs-progs#96]
If source and parent subvolumes are on different mountpoints, `btrfs send -p <parent> <source>` fails with memory corruption.

In cmds-send.c, it is wrongly assumed that source and parent share the same mountpoint [1], leading to subvol_strip_mountpoint() returning a char* pointer which can exceed the length of full_path (no bounds checking) [2].

  [1] https://github.com/kdave/btrfs-progs/blob/v4.15/cmds-send.c#L657
  [2] https://github.com/kdave/btrfs-progs/blob/v4.15/utils.c#L2490

Steps to reproduce:

```
# mkdir /tmp/btrfs_unittest
# truncate -s 200M /tmp/btrfs_unittest/btrfs0
# losetup /dev/loop0 /tmp/btrfs_unittest/btrfs0
# mkfs.btrfs -L BTRFS_UNITTEST /dev/loop0

# mkdir /tmp/btrfs_unittest/mnt_root
# mount /dev/loop0 /tmp/btrfs_unittest/mnt_root

# mkdir /tmp/btrfs_unittest/mnt_snapshots
# btrfs sub create /tmp/btrfs_unittest/mnt_root/snapshots
# mount -o subvol=snapshots /dev/loop0 /tmp/btrfs_unittest/mnt_snapshots

# btrfs sub create /tmp/btrfs_unittest/mnt_root/test0
# btrfs sub snap -r /tmp/btrfs_unittest/mnt_root/test0 /tmp/btrfs_unittest/mnt_snapshots/test0_snap_mnt_snapshots
# btrfs sub snap -r /tmp/btrfs_unittest/mnt_root/test0 /tmp/btrfs_unittest/mnt_root/test0_snap_mnt_root

# btrfs send -p /tmp/btrfs_unittest/mnt_snapshots/test0_snap_mnt_snapshots /tmp/btrfs_unittest/mnt_root/test0_snap_mnt_root > /dev/null
ERROR: open hots/test0_snap_mnt_snapshots failed. No such file or directory
ERROR: could not resolve rootid for /tmp/btrfs_unittest/mnt_snapshots/test0_snap_mnt_snapshots
```

**Comment by digint** [comment]
Added pull request: #98 

With the patch applied, the test above gives:
```
# btrfs send -p /tmp/btrfs_unittest/mnt_snapshots/test0_snap_mnt_snapshots /tmp/btrfs_unittest/mnt_root/test0_snap_mnt_root > /dev/null
ERROR: not on mount point: /tmp/btrfs_unittest/mnt_root
```

Still an error, but at least the memory corruption is gone.

**Comment by kdave** [comment]
I've created a testcase from the instruction you provided. Closing, thanks.

**Comment by niner** [comment]
This workaround seems to have killed btrfs send for me completely.
I have snapshots of / in /backup/ like /backup/sphinx-2018-04-29 and /backup/sphinx-2018-05-09
btrfs send -p /backup/sphinx-2018-04-29 /backup/sphinx-2018-05-09
always fails with "ERROR: not on mount point: /" which seems wrong since both snapshots definitely are on the same mount point. Only /sys, /proc, /dev, /run, /boot, /data and /backup/target are different file systems. Moving the snapshots out of /backup and into / did not help.
Downgrading btrfsprogs to 4.15 gave me a working backup again.

**Comment by digint** [comment]
I was able to reproduce this, and added pull request #138 which fixes this problem.
